### ISSUE TITLE
> /home/ahizzle/Backup/devicepathid/

### ISSUE THREAD

**Issue by BMWKingOC** [mvt-project/mvt#104]
> /home/ahizzle/Backup/devicepathid/
use the folder named by the UDID

_Originally posted by @p00perama in https://github.com/mvt-project/mvt/issues/93#issuecomment-886036729_

**Comment by BMWKingOC** [comment]
/home/ahizzle/Backup/devicepathid/

"devicepathid" is my uid. it's a long string of letters/ numbers...

home/ahizzle/Backup/UIDID/

ahizzle@ahizzle-virtual-machine:~$ mvt-ios decrypt-backup -p [pasword censored here] -d /home/ahizzle/ /home/ahizzle/Backup/udid[censored[
12:09:40 INFO [mvt.ios.decrypt] Decrypting iOS backup at path /home/ahizzle/Backup/udid[censored[ with password
12:09:46 ERROR [mvt.ios.decrypt] b'KEY'
Traceback (most recent call last):
File "/home/ahizzle/.local/lib/python3.8/site-packages/mvt/ios/decrypt.py", line 75, in decrypt_with_password
self._backup = iOSbackup(udid=os.path.basename(self.backup_path),
File "/home/ahizzle/.local/lib/python3.8/site-packages/iOSbackup/init.py", line 190, in init
self.getManifestDB()
File "/home/ahizzle/.local/lib/python3.8/site-packages/iOSbackup/init.py", line 1037, in getManifestDB
key = self.unwrapKeyForClass(manifest_class, manifest_key)
File "/home/ahizzle/.local/lib/python3.8/site-packages/iOSbackup/init.py", line 1150, in unwrapKeyForClass
ck = self.classKeys[protection_class][b"KEY"]
KeyError: b'KEY'
CRITICAL [mvt.ios.decrypt] Failed to decrypt backup. Did you provide the correct password?
Exception ignored in: <function iOSbackup.del at 0x7f6e6e7a9940>
Traceback (most recent call last):
File "/home/ahizzle/.local/lib/python3.8/site-packages/iOSbackup/init.py", line 132, in del
self.close()
File "/home/ahizzle/.local/lib/python3.8/site-packages/iOSbackup/init.py", line 138, in close
os.remove(self.manifestDB)
TypeError: remove: path should be string, bytes or os.PathLike, not NoneType

**Comment by botherder** [comment]
Please don't duplicate issues.
