### ISSUE TITLE
[IOS] check-iocs fails with `NameError: name 'SYSDIAGNOSE_MODULES' is not defined`

### ISSUE THREAD

**Issue by pab1it0** [mvt-project/mvt#105]
Running the following command:
`mvt-ios check-iocs --iocs /Users/pavelshklovsky/git/investigations/2021-07-18_nso/pegasus.stix2 /Users/pavelshklovsky/Documents/results`

Getting the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/mvt-ios", line 33, in <module>
    sys.exit(load_entry_point('mvt==1.0.11', 'console_scripts', 'mvt-ios')())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mvt/ios/cli.py", line 175, in check_iocs
    for entry in BACKUP_MODULES + FS_MODULES + SYSDIAGNOSE_MODULES:
NameError: name 'SYSDIAGNOSE_MODULES' is not defined
```

OS: macOS Big Sur 11.4

Kindly assist.

**Comment by botherder** [comment]
Please update from Git or wait for the upcoming version release.
