### ISSUE TITLE
mvt-android download-apks --output /home/gnarlin/Downloads/ --all-checks fails

### ISSUE THREAD

**Issue by gnarlin** [mvt-project/mvt#106]
Tried with both the version from the pip3 repo and by fetching the source myself. Same results.

Traceback (most recent call last):
  File "/home/gnarlin/.local/bin/mvt-android", line 8, in <module>
    sys.exit(cli())
  File "/home/gnarlin/.local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/gnarlin/.local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/gnarlin/.local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gnarlin/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gnarlin/.local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/gnarlin/.local/lib/python3.9/site-packages/mvt/android/cli.py", line 62, in download_apks
    download.run()
  File "/home/gnarlin/.local/lib/python3.9/site-packages/mvt/android/download_apks.py", line 208, in run
    self._adb_connect()
  File "/home/gnarlin/.local/lib/python3.9/site-packages/mvt/android/modules/adb/base.py", line 55, in _adb_connect
    self._adb_check_keys()
  File "/home/gnarlin/.local/lib/python3.9/site-packages/mvt/android/modules/adb/base.py", line 47, in _adb_check_keys
    keygen(ADB_KEY_PATH)
  File "/home/gnarlin/.local/lib/python3.9/site-packages/adb_shell/auth/keygen.py", line 248, in keygen
    with open(filepath, 'wb') as private_key_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/gnarlin/.android/adbkey'

**Comment by botherder** [comment]
You need to have adb keys created. Either do `adb keygen` or `adb shell` to let it set up properly.

**Comment by hamhicham** [comment]
i have also this problem
