### ISSUE TITLE
No device available, or it is in the wrong configuration

### ISSUE THREAD

**Issue by gnarlin** [mvt-project/mvt#115]
I did what you said in the previous bug. I created a key with adb keygen .android/adbkey (since that's the file that mvt-android complained was missing and you have to specify a file to create when you use adb keygen [file] ). But then when I run mvt-android download-apks --output /home/gnarlin/Downloads/ --all-checks I get a different error:

Traceback (most recent call last):
  File "/home/gnarlin/.local/lib/python3.9/site-packages/adb_shell/transport/usb_transport.py", line 597, in _find_first
    return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info, default_transport_timeout_s=default_transport_timeout_s))
StopIteration

During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "/home/gnarlin/.local/bin/mvt-android", line 8, in <module>
    sys.exit(cli())
  File "/home/gnarlin/.local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/gnarlin/.local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/gnarlin/.local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gnarlin/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gnarlin/.local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/gnarlin/.local/lib/python3.9/site-packages/mvt/android/cli.py", line 62, in download_apks
    download.run()
  File "/home/gnarlin/.local/lib/python3.9/site-packages/mvt/android/download_apks.py", line 208, in run
    self._adb_connect()
  File "/home/gnarlin/.local/lib/python3.9/site-packages/mvt/android/modules/adb/base.py", line 61, in _adb_connect
    self.device = AdbDeviceUsb()
  File "/home/gnarlin/.local/lib/python3.9/site-packages/adb_shell/adb_device.py", line 1500, in __init__
    transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
  File "/home/gnarlin/.local/lib/python3.9/site-packages/adb_shell/transport/usb_transport.py", line 620, in find_adb
    return cls._find(
  File "/home/gnarlin/.local/lib/python3.9/site-packages/adb_shell/transport/usb_transport.py", line 507, in _find
    return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info, default_transport_timeout_s=default_transport_timeout_s)
  File "/home/gnarlin/.local/lib/python3.9/site-packages/adb_shell/transport/usb_transport.py", line 599, in _find_first
    raise exceptions.UsbDeviceNotFoundError('No device available, or it is in the wrong configuration.')
adb_shell.exceptions.UsbDeviceNotFoundError: No device available, or it is in the wrong configuration.
```
My android phone is visible in the file system already and I can access it normally via file manager. What am I doing wrong?

**Comment by Te-k** [comment]
Can you access your phone through `adb shell`?

**Comment by quoidautre** [comment]
Hi,

Same error for me :(.
I'm using Linux Mint (up to date) and a Xiaomi Red Note 10 (version 12.0.1)
adb shell return :  

```
error : no devices/emulators found
```
When I plug the phone, Linux found him.

Regards

F.

**Comment by Te-k** [comment]
Then it is an adb issue, not an mvt issue. mvt just relies on adb to connect to the phone and extract data, if you cannot connect your phone through adb you have to debug that before using mvt.

**Comment by torta0** [comment]
I have a XiaoMi device - product:curtana_global model:Redmi_Note_9S

`ferreira@ferreira:~$ **adb version**
Android Debug Bridge version 1.0.39
Version 1:8.1.0+r23-5ubuntu2
Installed as /usr/lib/android-sdk/platform-tools/adb

ferreira@ferreira:~$ **adb shell**
curtana:/ $`

running the following code:

`ferreira@ferreira:~$ **mvt-android check-adb --output ./results**


        MVT - Mobile Verification Toolkit
                https://mvt.re
                Version: 1.4.1


23:56:45 INFO     [mvt.android.cli] Checking Android through adb bridge
         INFO     [mvt.android.cli] Loaded a total of 0 indicators
         INFO     [mvt.android.modules.adb.chrome_history] Running module ChromeHistory...
         ERROR    [mvt.android.modules.adb.chrome_history] Error in running extraction from module ChromeHistory: No
                  device available, or it is in the wrong configuration.
                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  601, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                  StopIteration

                  During handling of the above exception, another exception occurred:

                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/common/module.py", line 153, in
                  run_module
                      module.run()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/chrome_history.py",
                  line 81, in run
                      self._adb_process_file(os.path.join("/", CHROME_HISTORY_PATH),
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 212,
                  in _adb_process_file
                      self._adb_connect()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 68,
                  in _adb_connect
                      self.device = AdbDeviceUsb(serial=self.serial)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1524, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  624, in find_adb
                      return cls._find(
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  512, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  603, in _find_first
                      raise exceptions.UsbDeviceNotFoundError('No device available, or it is in the wrong
                  configuration.')
                  adb_shell.exceptions.UsbDeviceNotFoundError: No device available, or it is in the wrong configuration.
         INFO     [mvt.android.modules.adb.sms] Running module SMS...
         ERROR    [mvt.android.modules.adb.sms] Error in running extraction from module SMS: No device available, or it
                  is in the wrong configuration.
                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  601, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                  StopIteration

                  During handling of the above exception, another exception occurred:

                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/common/module.py", line 153, in
                  run_module
                      module.run()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/sms.py", line 108,
                  in run
                      if (self._adb_check_file_exists(os.path.join("/", SMS_BUGLE_PATH))):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 151,
                  in _adb_check_file_exists
                      self._adb_connect()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 68,
                  in _adb_connect
                      self.device = AdbDeviceUsb(serial=self.serial)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1524, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  624, in find_adb
                      return cls._find(
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  512, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  603, in _find_first
                      raise exceptions.UsbDeviceNotFoundError('No device available, or it is in the wrong
                  configuration.')
                  adb_shell.exceptions.UsbDeviceNotFoundError: No device available, or it is in the wrong configuration.
         INFO     [mvt.android.modules.adb.whatsapp] Running module Whatsapp...
         ERROR    [mvt.android.modules.adb.whatsapp] Error in running extraction from module Whatsapp: No device
                  available, or it is in the wrong configuration.
                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  601, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                  StopIteration

                  During handling of the above exception, another exception occurred:

                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/common/module.py", line 153, in
                  run_module
                      module.run()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/whatsapp.py", line
                  88, in run
                      self._adb_process_file(os.path.join("/", WHATSAPP_PATH), self._parse_db)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 212,
                  in _adb_process_file
                      self._adb_connect()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 68,
                  in _adb_connect
                      self.device = AdbDeviceUsb(serial=self.serial)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1524, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  624, in find_adb
                      return cls._find(
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  512, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  603, in _find_first
                      raise exceptions.UsbDeviceNotFoundError('No device available, or it is in the wrong
                  configuration.')
                  adb_shell.exceptions.UsbDeviceNotFoundError: No device available, or it is in the wrong configuration.
         INFO     [mvt.android.modules.adb.processes] Running module Processes...
         ERROR    [mvt.android.modules.adb.processes] Error in running extraction from module Processes: No device
                  available, or it is in the wrong configuration.
                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  601, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                  StopIteration

                  During handling of the above exception, another exception occurred:

                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/common/module.py", line 153, in
                  run_module
                      module.run()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/processes.py", line
                  23, in run
                      self._adb_connect()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 68,
                  in _adb_connect
                      self.device = AdbDeviceUsb(serial=self.serial)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1524, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  624, in find_adb
                      return cls._find(
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  512, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  603, in _find_first
                      raise exceptions.UsbDeviceNotFoundError('No device available, or it is in the wrong
                  configuration.')
                  adb_shell.exceptions.UsbDeviceNotFoundError: No device available, or it is in the wrong configuration.
         INFO     [mvt.android.modules.adb.dumpsys_batterystats] Running module DumpsysBatterystats...
         ERROR    [mvt.android.modules.adb.dumpsys_batterystats] Error in running extraction from module
                  DumpsysBatterystats: No device available, or it is in the wrong configuration.
                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  601, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                  StopIteration

                  During handling of the above exception, another exception occurred:

                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/common/module.py", line 153, in
                  run_module
                      module.run()
                    File
                  "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/dumpsys_batterystats.py",
                  line 24, in run
                      self._adb_connect()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 68,
                  in _adb_connect
                      self.device = AdbDeviceUsb(serial=self.serial)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1524, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  624, in find_adb
                      return cls._find(
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  512, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  603, in _find_first
                      raise exceptions.UsbDeviceNotFoundError('No device available, or it is in the wrong
                  configuration.')
                  adb_shell.exceptions.UsbDeviceNotFoundError: No device available, or it is in the wrong configuration.
         INFO     [mvt.android.modules.adb.dumpsys_procstats] Running module DumpsysProcstats...
         ERROR    [mvt.android.modules.adb.dumpsys_procstats] Error in running extraction from module DumpsysProcstats:
                  No device available, or it is in the wrong configuration.
                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  601, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                  StopIteration

                  During handling of the above exception, another exception occurred:

                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/common/module.py", line 153, in
                  run_module
                      module.run()
                    File
                  "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/dumpsys_procstats.py", line
                  24, in run
                      self._adb_connect()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 68,
                  in _adb_connect
                      self.device = AdbDeviceUsb(serial=self.serial)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1524, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  624, in find_adb
                      return cls._find(
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  512, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  603, in _find_first
                      raise exceptions.UsbDeviceNotFoundError('No device available, or it is in the wrong
                  configuration.')
                  adb_shell.exceptions.UsbDeviceNotFoundError: No device available, or it is in the wrong configuration.
         INFO     [mvt.android.modules.adb.dumpsys_packages] Running module DumpsysPackages...
         ERROR    [mvt.android.modules.adb.dumpsys_packages] Error in running extraction from module DumpsysPackages: No
                  device available, or it is in the wrong configuration.
                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  601, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                  StopIteration

                  During handling of the above exception, another exception occurred:

                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/common/module.py", line 153, in
                  run_module
                      module.run()
                    File
                  "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/dumpsys_packages.py", line
                  24, in run
                      self._adb_connect()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 68,
                  in _adb_connect
                      self.device = AdbDeviceUsb(serial=self.serial)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1524, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  624, in find_adb
                      return cls._find(
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  512, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  603, in _find_first
                      raise exceptions.UsbDeviceNotFoundError('No device available, or it is in the wrong
                  configuration.')
                  adb_shell.exceptions.UsbDeviceNotFoundError: No device available, or it is in the wrong configuration.
         INFO     [mvt.android.modules.adb.dumpsys_receivers] Running module DumpsysReceivers...
         ERROR    [mvt.android.modules.adb.dumpsys_receivers] Error in running extraction from module DumpsysReceivers:
                  No device available, or it is in the wrong configuration.
                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  601, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                  StopIteration

                  During handling of the above exception, another exception occurred:

                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/common/module.py", line 153, in
                  run_module
                      module.run()
                    File
                  "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/dumpsys_receivers.py", line
                  28, in run
                      self._adb_connect()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 68,
                  in _adb_connect
                      self.device = AdbDeviceUsb(serial=self.serial)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1524, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  624, in find_adb
                      return cls._find(
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  512, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  603, in _find_first
                      raise exceptions.UsbDeviceNotFoundError('No device available, or it is in the wrong
                  configuration.')
                  adb_shell.exceptions.UsbDeviceNotFoundError: No device available, or it is in the wrong configuration.
         INFO     [mvt.android.modules.adb.dumpsys_full] Running module DumpsysFull...
         ERROR    [mvt.android.modules.adb.dumpsys_full] Error in running extraction from module DumpsysFull: No device
                  available, or it is in the wrong configuration.
                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  601, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                  StopIteration

                  During handling of the above exception, another exception occurred:

                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/common/module.py", line 153, in
                  run_module
                      module.run()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/dumpsys_full.py",
                  line 24, in run
                      self._adb_connect()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 68,
                  in _adb_connect
                      self.device = AdbDeviceUsb(serial=self.serial)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1524, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  624, in find_adb
                      return cls._find(
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  512, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  603, in _find_first
                      raise exceptions.UsbDeviceNotFoundError('No device available, or it is in the wrong
                  configuration.')
                  adb_shell.exceptions.UsbDeviceNotFoundError: No device available, or it is in the wrong configuration.
         INFO     [mvt.android.modules.adb.packages] Running module Packages...
         ERROR    [mvt.android.modules.adb.packages] Error in running extraction from module Packages: No device
                  available, or it is in the wrong configuration.
                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  601, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                  StopIteration

                  During handling of the above exception, another exception occurred:

                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/common/module.py", line 153, in
                  run_module
                      module.run()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/packages.py", line
                  95, in run
                      self._adb_connect()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 68,
                  in _adb_connect
                      self.device = AdbDeviceUsb(serial=self.serial)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1524, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  624, in find_adb
                      return cls._find(
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  512, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  603, in _find_first
                      raise exceptions.UsbDeviceNotFoundError('No device available, or it is in the wrong
                  configuration.')
                  adb_shell.exceptions.UsbDeviceNotFoundError: No device available, or it is in the wrong configuration.
         INFO     [mvt.android.modules.adb.rootbinaries] Running module RootBinaries...
         ERROR    [mvt.android.modules.adb.rootbinaries] Error in running extraction from module RootBinaries: No device
                  available, or it is in the wrong configuration.
                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  601, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                  StopIteration

                  During handling of the above exception, another exception occurred:

                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/common/module.py", line 153, in
                  run_module
                      module.run()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/rootbinaries.py",
                  line 30, in run
                      self._adb_connect()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 68,
                  in _adb_connect
                      self.device = AdbDeviceUsb(serial=self.serial)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1524, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  624, in find_adb
                      return cls._find(
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  512, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  603, in _find_first
                      raise exceptions.UsbDeviceNotFoundError('No device available, or it is in the wrong
                  configuration.')
                  adb_shell.exceptions.UsbDeviceNotFoundError: No device available, or it is in the wrong configuration.
         INFO     [mvt.android.modules.adb.logcat] Running module Logcat...
         ERROR    [mvt.android.modules.adb.logcat] Error in running extraction from module Logcat: No device available,
                  or it is in the wrong configuration.
                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  601, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                  StopIteration

                  During handling of the above exception, another exception occurred:

                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/common/module.py", line 153, in
                  run_module
                      module.run()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/logcat.py", line 24,
                  in run
                      self._adb_connect()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 68,
                  in _adb_connect
                      self.device = AdbDeviceUsb(serial=self.serial)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1524, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  624, in find_adb
                      return cls._find(
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  512, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  603, in _find_first
                      raise exceptions.UsbDeviceNotFoundError('No device available, or it is in the wrong
                  configuration.')
                  adb_shell.exceptions.UsbDeviceNotFoundError: No device available, or it is in the wrong configuration.
         INFO     [mvt.android.modules.adb.files] Running module Files...
         ERROR    [mvt.android.modules.adb.files] Error in running extraction from module Files: No device available, or
                  it is in the wrong configuration.
                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  601, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                  StopIteration

                  During handling of the above exception, another exception occurred:

                  Traceback (most recent call last):
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/common/module.py", line 153, in
                  run_module
                      module.run()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/files.py", line 102,
                  in run
                      self._adb_connect()
                    File "/home/ferreira/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 68,
                  in _adb_connect
                      self.device = AdbDeviceUsb(serial=self.serial)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1524, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  624, in find_adb
                      return cls._find(
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  512, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/ferreira/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  603, in _find_first
                      raise exceptions.UsbDeviceNotFoundError('No device available, or it is in the wrong
                  configuration.')
                  adb_shell.exceptions.UsbDeviceNotFoundError: No device available, or it is in the wrong configuration.`
