### ISSUE TITLE
Error while running mvt-ios decrypt-backup or mvt-ios check-backup

### ISSUE THREAD

**Issue by Ashwed** [mvt-project/mvt#117]
Hello!

I get this error when I am running either of the mvt-ios commands: 
```
_Traceback (most recent call last):
  File "/Users/ashwedsmacbookpro/opt/anaconda3/bin/mvt-ios", line 5, in <module>
    from mvt.ios import cli
  File "/Users/ashwedsmacbookpro/opt/anaconda3/lib/python3.7/site-packages/mvt/ios/__init__.py", line 6, in <module>
    from .cli import cli
  File "/Users/ashwedsmacbookpro/opt/anaconda3/lib/python3.7/site-packages/mvt/ios/cli.py", line 52, in <module>
    @click.argument("BACKUP_PATH", type=click.Path(exists=True))
  File "/Users/ashwedsmacbookpro/opt/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 173, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/Users/ashwedsmacbookpro/opt/anaconda3/lib/python3.7/site-packages/mvt/common/options.py", line 23, in __init__
    super(MutuallyExclusiveOption, self).__init__(*args, **kwargs)
  File "/Users/ashwedsmacbookpro/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 1547, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'prompt_required'_
```

I would appreciate it if someone could help me resolve this issue!

**Comment by sanjaydemansol** [comment]
@sanjaydemansol a comment.

**Comment by sanjaydemansol** [comment]
@sanjaydemansol another.

**Comment by Te-k** [comment]
Can you share the result of `pip list` here?

**Comment by botherder** [comment]
You likely had an outdated version of click. This is no longer necessary, upgrade mvt to latest version.
