### ISSUE TITLE
mvt-android check-adb return me an exception: KeyError: 'mvt/android/modules/adb/../../data/root_packages.txt'

### ISSUE THREAD

**Issue by michelep** [mvt-project/mvt#118]
Latest ADB and latest GitHub release.

Running mvt-android check-adb return me this:
```
09:30:48 INFO     [mvt.android.modules.adb.dumpsys_procstats] Running module DumpsysProcstats...                                                                                                                                              
09:30:49 INFO     [mvt.android.modules.adb.dumpsys_packages] Running module DumpsysPackages...                                                                                                                                                
09:30:55 INFO     [mvt.android.modules.adb.packages] Running module Packages...                                                                                                                                                               
09:31:35 INFO     [mvt.android.modules.adb.packages] Extracted at total of 478 installed package names                                                                                                                                        
Traceback (most recent call last):
  File "<frozen zipimport>", line 177, in get_data
KeyError: 'mvt/android/modules/adb/../../data/root_packages.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mvt-android", line 11, in <module>
    load_entry_point('mvt==1.0.12', 'console_scripts', 'mvt-android')()
  File "/usr/local/lib/python3.8/dist-packages/click-8.0.1-py3.8.egg/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click-8.0.1-py3.8.egg/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click-8.0.1-py3.8.egg/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click-8.0.1-py3.8.egg/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click-8.0.1-py3.8.egg/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mvt-1.0.12-py3.8.egg/mvt/android/cli.py", line 115, in check_adb
  File "/usr/local/lib/python3.8/dist-packages/mvt-1.0.12-py3.8.egg/mvt/common/module.py", line 160, in run_module
  File "/usr/local/lib/python3.8/dist-packages/mvt-1.0.12-py3.8.egg/mvt/android/modules/adb/packages.py", line 44, in check_indicators
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1157, in resource_string
    return get_provider(package_or_requirement).get_resource_string(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1402, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1570, in _get
    return self.loader.get_data(path)
  File "<frozen zipimport>", line 179, in get_data
OSError: [Errno 0] : 'mvt/android/modules/adb/../../data/root_packages.txt'
```

**Comment by botherder** [comment]
I am not able to reproduce this. Can you share how you installed and how you launched mvt?

**Comment by Te-k** [comment]
As this issue has been inactive for more than 6 month, I am closing it
