### ISSUE TITLE
ERROR on iOS 15 BETA3  (Error in running extraction from module Contacts: no such table: ABPerson)

### ISSUE THREAD

**Issue by corsch** [mvt-project/mvt#119]
I've got an issue with an iOS 15 (BETA 3) backup.

 mvt-ios check-backup -i investigations/2021-07-18_nso/pegasus.stix2 -o /mnt/c/temp/erg/ /mnt/c/temp/decrypted/

```
    ERROR    [mvt.ios.modules.fs.contacts] Error in running extraction from module Contacts: no such table: ABPerson
                  Traceback (most recent call last):
                    File "/usr/local/lib/python3.8/dist-packages/mvt/common/module.py", line 145, in run_module
                      module.run()
                    File "/usr/local/lib/python3.8/dist-packages/mvt/ios/modules/fs/contacts.py", line 32, in run
                      cur.execute("""
                  sqlite3.OperationalError: no such table: ABPerson
```

Is an iOS 15 backup already supported?

**Comment by Te-k** [comment]
No, it has not been tested yet, I guess there were some changes in the contacts format
