### ISSUE TITLE
SMS Module: UnicodeEncodeError: 'charmap' codec can't encode characters in position 320-321: character maps to <undefined>

### ISSUE THREAD

**Issue by securityvoid** [mvt-project/mvt#12]
The SMS Module is erroring out for me. The backup was created with iTunes:

```
21:44:00 INFO     [mvt.ios.cli] Checking iTunes backup located at: **REDACTED**
         INFO     [mvt.ios.modules.fs.sms] Running module SMS...
         INFO     [mvt.ios.modules.fs.sms] Found SMS database at path: **REDACTED**
21:44:02 INFO     [mvt.ios.modules.fs.sms] Extracted a total of 1710 SMS messages containing links
Traceback (most recent call last):
  File "C:\Python39\Scripts\mvt-ios-script.py", line 33, in <module>
    sys.exit(load_entry_point('mvt==1.0.11', 'console_scripts', 'mvt-ios')())
  File "c:\python39\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\python39\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\python39\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python39\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\python39\lib\site-packages\mvt\ios\cli.py", line 108, in check_backup
    save_timeline(timeline, os.path.join(output, "timeline.csv"))
  File "c:\python39\lib\site-packages\mvt\common\module.py", line 167, in save_timeline
    csvoutput.writerow([
  File "c:\python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 320-321: character maps to <undefined>
```

**Comment by securityvoid** [comment]
The above is with iOS 14.2 on an iPhone 8 Plus, Model Number NQ962LL/A.

This is the whole tool output:
```
22:06:40 INFO     [mvt.ios.cli] Checking iTunes backup located at: ./backup/**REDACTED**
         INFO     [mvt.ios.modules.fs.safari_browserstate] Running module SafariBrowserState...
         ERROR    [mvt.ios.modules.fs.safari_browserstate] There might be no data to extract by module SafariBrowserState: Unable to find the module's database file
         INFO     [mvt.ios.modules.fs.safari_history] Running module SafariHistory...
         ERROR    [mvt.ios.modules.fs.safari_history] There might be no data to extract by module SafariHistory: Unable to find the module's database file
         INFO     [mvt.ios.modules.fs.net_datausage] Running module Datausage...
         INFO     [mvt.ios.modules.fs.net_datausage] Found DataUsage database at path: ./backup/**REDACTED**\0d\0d609c54856a9bb2d56729df1d68f2958a88426b
22:06:41 INFO     [mvt.ios.modules.fs.net_datausage] Extracted information on 3036 processes
         INFO     [mvt.ios.modules.fs.sms] Running module SMS...
         INFO     [mvt.ios.modules.fs.sms] Found SMS database at path: ./backup/**REDACTED**\3d\3d0d7e5fb2ce288813306e4d4636395e047a3d28
22:06:42 INFO     [mvt.ios.modules.fs.sms] Extracted a total of 1710 SMS messages containing links
22:06:43 INFO     [mvt.ios.modules.fs.sms_attachments] Running module SMSAttachments...
         INFO     [mvt.ios.modules.fs.sms_attachments] Found SMS database at path: ./backup/**REDACTED**\3d\3d0d7e5fb2ce288813306e4d4636395e047a3d28
         INFO     [mvt.ios.modules.fs.sms_attachments] Extracted a total of 2464 SMS attachments
         INFO     [mvt.ios.modules.fs.chrome_history] Running module ChromeHistory...
         ERROR    [mvt.ios.modules.fs.chrome_history] There might be no data to extract by module ChromeHistory: Unable to find the module's database file
         INFO     [mvt.ios.modules.fs.chrome_favicon] Running module ChromeFavicon...
         ERROR    [mvt.ios.modules.fs.chrome_favicon] There might be no data to extract by module ChromeFavicon: Unable to find the module's database file
         INFO     [mvt.ios.modules.fs.webkit_session_resource_log] Running module WebkitSessionResourceLog...
         INFO     [mvt.ios.modules.fs.calls] Running module Calls...
         ERROR    [mvt.ios.modules.fs.calls] There might be no data to extract by module Calls: Unable to find the module's database file
         INFO     [mvt.ios.modules.fs.idstatuscache] Running module IDStatusCache...
         INFO     [mvt.ios.modules.fs.idstatuscache] Found IDStatusCache plist at path: ./backup/**REDACTED**\6b\6b97989189901ceaa4e5be9b7f05fb584120e27b
         INFO     [mvt.ios.modules.fs.idstatuscache] Extracted a total of 4136 ID Status Cache entries
22:06:44 INFO     [mvt.ios.modules.fs.locationd] Running module LocationdClients...
         INFO     [mvt.ios.modules.fs.locationd] Found Locationd Clients plist at path: ./backup/**REDACTED**\a6\a690d7769cce8904ca2b67320b107c8fe5f79412
         INFO     [mvt.ios.modules.fs.locationd] Extracted a total of 0 Locationd Clients entries
         INFO     [mvt.ios.modules.fs.interactionc] Running module InteractionC...
         ERROR    [mvt.ios.modules.fs.interactionc] There might be no data to extract by module InteractionC: Unable to find the module's database file
         INFO     [mvt.ios.modules.fs.firefox_history] Running module FirefoxHistory...
         ERROR    [mvt.ios.modules.fs.firefox_history] There might be no data to extract by module FirefoxHistory: Unable to find the module's database file
         INFO     [mvt.ios.modules.fs.firefox_favicon] Running module FirefoxFavicon...
         ERROR    [mvt.ios.modules.fs.firefox_favicon] There might be no data to extract by module FirefoxFavicon: Unable to find the module's database file
         INFO     [mvt.ios.modules.fs.contacts] Running module Contacts...
         INFO     [mvt.ios.modules.fs.contacts] Found Contacts database at path: ./backup/**REDACTED**\31\31bb7ba8914766d4ba40d6dfb6113c8b614be442
         INFO     [mvt.ios.modules.fs.contacts] Extracted a total of 916 contacts from the address book
         INFO     [mvt.ios.modules.fs.manifest] Running module Manifest...
         INFO     [mvt.ios.modules.fs.manifest] Found Manifest.db database at path: ./backup/**REDACTED**\Manifest.db
22:06:54 INFO     [mvt.ios.modules.fs.manifest] Extracted a total of 51817 file metadata items
22:06:56 INFO     [mvt.ios.modules.fs.whatsapp] Running module Whatsapp...
         ERROR    [mvt.ios.modules.fs.whatsapp] There might be no data to extract by module Whatsapp: Unable to find the module's database file
```

There really should have been Safari history.

**Comment by botherder** [comment]
I'm confused. You are showing outputs of two different backups? Or why is the first erroring and the second not?

Regarding Safari history, if the backup wasn't encrypted Safari history is not included.

**Comment by botherder** [comment]
Closing this, as the first issue should have been fixed.
