### ISSUE TITLE
[ubuntu on wsl] usb1.USBErrorOther: LIBUSB_ERROR_OTHER [-99]

### ISSUE THREAD

**Issue by MajdShoots** [mvt-project/mvt#125]
I'm still new to this all of this, and I've tried to search the web for a solution without any success. so here I am making a fool of myself and posting my issue here to hopefully find a solution for (because I REALLY need to make sure my phone doesn't have this software in it as it may pose a risk to my life)
my device doesn't show up when I try the adb devices command, even though I downloaded the adb driver on windows.
can I please be walked through this like the noob I am
thank you very much for your effort

**Comment by abhishekbaghel** [comment]
If your device shows up when you execute adb devices from the windows machine and not when executing the same command in WSL Ubuntu, the following steps can help you - 

On the Windows side:

adb.exe -a -P 5037 nodaemon server

On the WSL2 side:

export ADB_SERVER_SOCKET=tcp:192.168.1.100:5037

adb devices

where 192.68.1.100 is your Windows machine IP.

Make sure both  WSL Ubuntu and Windows are running the same version of adb using - adb version

**Comment by moonkit** [comment]
Try: apt install libusb-dev

**Comment by nextgen-networks** [comment]
> If your device shows up when you execute adb devices from the windows machine and not when executing the same command in WSL Ubuntu, the following steps can help you -
> 
> On the Windows side:
> 
> adb.exe -a -P 5037 nodaemon server
> 
> On the WSL2 side:
> 
> export ADB_SERVER_SOCKET=tcp:192.168.1.100:5037
> 
> adb devices
> 
> where 192.68.1.100 is your Windows machine IP.
> 
> Make sure both WSL Ubuntu and Windows are running the same version of adb using - adb version

facing the same issue.
Thanks to instructions that are similar to those  you @abhishekbaghel wrote the device shows in adb devices but error persists.

Here is the complete output I got (sorry format/linebreaks seem to be doomed when inserting as code):
`
WSLuserName@WSLdeviceName:~$ adb devices
List of devices attached
SeRiAlOfDeViCe        device
WSLuserName@WSLdeviceName:~$ mvt-android check-adb
22:24:26 INFO     [mvt.android.cli] Checking Android through adb bridge
         INFO     [mvt.android.modules.adb.chrome_history] Running module ChromeHistory...
         ERROR    [mvt.android.modules.adb.chrome_history] Error in running extraction from module ChromeHistory:
                  LIBUSB_ERROR_OTHER [-99]
                  Traceback (most recent call last):
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/common/module.py", line 149, in
                  run_module
                      module.run()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/android/modules/adb/chrome_history.py",
                  line 70, in run
                      self._adb_process_file(os.path.join("/", CHROME_HISTORY_PATH),
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 180,
                  in _adb_process_file
                      self._adb_connect()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 62,
                  in _adb_connect
                      self.device = AdbDeviceUsb()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1500, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  620, in find_adb
                      return cls._find(
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  507, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  597, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  559, in _find_devices
                      for device in ctx.getDeviceList(skip_on_error=True):
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2226, in
                  getDeviceList
                      return list(
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2084, in wrapper
                      with refcount(self):
                    File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
                      return next(self.gen)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2073, in refcount
                      self.open()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2139, in open
                      mayRaiseUSBError(libusb1.libusb_init(byref(self.__context_p)))
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 127, in
                  mayRaiseUSBError
                      __raiseUSBError(value)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 119, in
                  raiseUSBError
                      raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
                  usb1.USBErrorOther: LIBUSB_ERROR_OTHER [-99]
         INFO     [mvt.android.modules.adb.sms] Running module SMS...
         ERROR    [mvt.android.modules.adb.sms] LIBUSB_ERROR_OTHER [-99]
         INFO     [mvt.android.modules.adb.whatsapp] Running module Whatsapp...
         ERROR    [mvt.android.modules.adb.whatsapp] LIBUSB_ERROR_OTHER [-99]
         INFO     [mvt.android.modules.adb.processes] Running module Processes...
         ERROR    [mvt.android.modules.adb.processes] Error in running extraction from module Processes:
                  LIBUSB_ERROR_OTHER [-99]
                  Traceback (most recent call last):
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/common/module.py", line 149, in
                  run_module
                      module.run()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/android/modules/adb/processes.py", line
                  22, in run
                      self._adb_connect()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 62,
                  in _adb_connect
                      self.device = AdbDeviceUsb()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1500, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  620, in find_adb
                      return cls._find(
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  507, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  597, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  559, in _find_devices
                      for device in ctx.getDeviceList(skip_on_error=True):
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2226, in
                  getDeviceList
                      return list(
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2084, in wrapper
                      with refcount(self):
                    File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
                      return next(self.gen)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2073, in refcount
                      self.open()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2139, in open
                      mayRaiseUSBError(libusb1.libusb_init(byref(self.__context_p)))
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 127, in
                  mayRaiseUSBError
                      __raiseUSBError(value)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 119, in
                  raiseUSBError
                      raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
                  usb1.USBErrorOther: LIBUSB_ERROR_OTHER [-99]
         INFO     [mvt.android.modules.adb.dumpsys_batterystats] Running module DumpsysBatterystats...
         ERROR    [mvt.android.modules.adb.dumpsys_batterystats] Error in running extraction from module
                  DumpsysBatterystats: LIBUSB_ERROR_OTHER [-99]
                  Traceback (most recent call last):
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/common/module.py", line 149, in
                  run_module
                      module.run()
                    File
                  "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/android/modules/adb/dumpsys_batterystats.py",
                  line 23, in run
                      self._adb_connect()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 62,
                  in _adb_connect
                      self.device = AdbDeviceUsb()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1500, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  620, in find_adb
                      return cls._find(
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  507, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  597, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  559, in _find_devices
                      for device in ctx.getDeviceList(skip_on_error=True):
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2226, in
                  getDeviceList
                      return list(
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2084, in wrapper
                      with refcount(self):
                    File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
                      return next(self.gen)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2073, in refcount
                      self.open()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2139, in open
                      mayRaiseUSBError(libusb1.libusb_init(byref(self.__context_p)))
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 127, in
                  mayRaiseUSBError
                      __raiseUSBError(value)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 119, in
                  raiseUSBError
                      raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
                  usb1.USBErrorOther: LIBUSB_ERROR_OTHER [-99]
         INFO     [mvt.android.modules.adb.dumpsys_procstats] Running module DumpsysProcstats...
         ERROR    [mvt.android.modules.adb.dumpsys_procstats] Error in running extraction from module DumpsysProcstats:
                  LIBUSB_ERROR_OTHER [-99]
                  Traceback (most recent call last):
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/common/module.py", line 149, in
                  run_module
                      module.run()
                    File
                  "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/android/modules/adb/dumpsys_procstats.py",
                  line 23, in run
                      self._adb_connect()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 62,
                  in _adb_connect
                      self.device = AdbDeviceUsb()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1500, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  620, in find_adb
                      return cls._find(
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  507, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  597, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  559, in _find_devices
                      for device in ctx.getDeviceList(skip_on_error=True):
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2226, in
                  getDeviceList
                      return list(
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2084, in wrapper
                      with refcount(self):
                    File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
                      return next(self.gen)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2073, in refcount
                      self.open()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2139, in open
                      mayRaiseUSBError(libusb1.libusb_init(byref(self.__context_p)))
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 127, in
                  mayRaiseUSBError
                      __raiseUSBError(value)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 119, in
                  raiseUSBError
                      raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
                  usb1.USBErrorOther: LIBUSB_ERROR_OTHER [-99]
         INFO     [mvt.android.modules.adb.dumpsys_packages] Running module DumpsysPackages...
         ERROR    [mvt.android.modules.adb.dumpsys_packages] Error in running extraction from module DumpsysPackages:
                  LIBUSB_ERROR_OTHER [-99]
                  Traceback (most recent call last):
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/common/module.py", line 149, in
                  run_module
                      module.run()
                    File
                  "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/android/modules/adb/dumpsys_packages.py", line
                  23, in run
                      self._adb_connect()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 62,
                  in _adb_connect
                      self.device = AdbDeviceUsb()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1500, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  620, in find_adb
                      return cls._find(
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  507, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  597, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  559, in _find_devices
                      for device in ctx.getDeviceList(skip_on_error=True):
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2226, in
                  getDeviceList
                      return list(
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2084, in wrapper
                      with refcount(self):
                    File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
                      return next(self.gen)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2073, in refcount
                      self.open()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2139, in open
                      mayRaiseUSBError(libusb1.libusb_init(byref(self.__context_p)))
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 127, in
                  mayRaiseUSBError
                      __raiseUSBError(value)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 119, in
                  raiseUSBError
                      raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
                  usb1.USBErrorOther: LIBUSB_ERROR_OTHER [-99]
         INFO     [mvt.android.modules.adb.packages] Running module Packages...
         ERROR    [mvt.android.modules.adb.packages] Error in running extraction from module Packages:
                  LIBUSB_ERROR_OTHER [-99]
                  Traceback (most recent call last):
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/common/module.py", line 149, in
                  run_module
                      module.run()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/android/modules/adb/packages.py", line
                  59, in run
                      self._adb_connect()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 62,
                  in _adb_connect
                      self.device = AdbDeviceUsb()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1500, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  620, in find_adb
                      return cls._find(
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  507, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  597, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  559, in _find_devices
                      for device in ctx.getDeviceList(skip_on_error=True):
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2226, in
                  getDeviceList
                      return list(
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2084, in wrapper
                      with refcount(self):
                    File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
                      return next(self.gen)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2073, in refcount
                      self.open()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2139, in open
                      mayRaiseUSBError(libusb1.libusb_init(byref(self.__context_p)))
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 127, in
                  mayRaiseUSBError
                      __raiseUSBError(value)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 119, in
                  raiseUSBError
                      raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
                  usb1.USBErrorOther: LIBUSB_ERROR_OTHER [-99]
         INFO     [mvt.android.modules.adb.rootbinaries] Running module RootBinaries...
         ERROR    [mvt.android.modules.adb.rootbinaries] Error in running extraction from module RootBinaries:
                  LIBUSB_ERROR_OTHER [-99]
                  Traceback (most recent call last):
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/common/module.py", line 149, in
                  run_module
                      module.run()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/android/modules/adb/rootbinaries.py",
                  line 29, in run
                      self._adb_connect()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 62,
                  in _adb_connect
                      self.device = AdbDeviceUsb()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 1500, in
                  __init__
                      transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  620, in find_adb
                      return cls._find(
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  507, in _find
                      return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  597, in _find_first
                      return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info,
                  default_transport_timeout_s=default_transport_timeout_s))
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line
                  559, in _find_devices
                      for device in ctx.getDeviceList(skip_on_error=True):
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2226, in
                  getDeviceList
                      return list(
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2084, in wrapper
                      with refcount(self):
                    File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
                      return next(self.gen)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2073, in refcount
                      self.open()
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2139, in open
                      mayRaiseUSBError(libusb1.libusb_init(byref(self.__context_p)))
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 127, in
                  mayRaiseUSBError
                      __raiseUSBError(value)
                    File "/home/WSLuserName/.local/lib/python3.8/site-packages/usb1/__init__.py", line 119, in
                  raiseUSBError
                      raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
                  usb1.USBErrorOther: LIBUSB_ERROR_OTHER [-99]`

**Comment by MajdShoots** [comment]
> If your device shows up when you execute adb devices from the windows machine and not when executing the same command in WSL Ubuntu, the following steps can help you -
> 
> On the Windows side:
> 
> adb.exe -a -P 5037 nodaemon server
> 
> On the WSL2 side:
> 
> export ADB_SERVER_SOCKET=tcp:192.168.1.100:5037
> 
> adb devices
> 
> where 192.68.1.100 is your Windows machine IP.
> 
> Make sure both WSL Ubuntu and Windows are running the same version of adb using - adb version

it didn't show up on windows and ubuntu WSL after I tried to install the drivers on for both, it just returned an empty list when executed
but I installed a full version of Ubuntu on my windows laptop as a dual boot and now I'm facing a whole other array of problems :), thanks for your help guys

**Comment by botherder** [comment]
@nextgen-networks do you have lisbusb installed?

**Comment by nextgen-networks** [comment]
> @nextgen-networks do you have lisbusb installed?

Hi @botherder,
yepp, installed it right before the test and log creation.

**Comment by Naimad1CZ** [comment]
I tried to use WSL too.
Downloaded (and extracted) adb 1.0.39 from here: https://forum.xda-developers.com/t/tool-latest-adb-and-fastboot-for-win-linux-and-mac.3592629/
Installed adb on Ubuntu WSL (`adb version` is 1.0.39).
Got to Developer settings on Android, enabled USB debugging (if you tried those stuff before and your device shows as unauthorized after `adb devices`, then plug out phone, click on "Revoke USB debugging authorizations", maybe disable and enable USB debuging) and Default USB configuration -> Transfering files. 
Then opened (tried administrator) Powershell (migh be "cross-platform" PowerShell (7.1.3) or usual Windows PowerShell) in a folder with extracted adb, then `.\sdb start-server` -> click Ok on phone when it asks for authorizing -> `.\adb devices` to check that it writes "<my device code> device" -> run (tried administrator) WSL -> `mvt-android download-apks --output /mnt/c/LocalPrograms/apkoutp` -> got error, stack trace:
```
File "/home/<myname>/.local/bin/mvt-android", line 8, in <module>
    sys.exit(cli())
...
...
...
File "/home/<myname>/.local/lib/python3.8/site-packages/usb1/__init__.py", line 119, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorOther: LIBUSB_ERROR_OTHER [-99]
```

I would be glad if someone provided a way how to fix it or some instructions how to perform it from some Linux in VirtualBox.

**Comment by KygekDev** [comment]
I'm also facing the same issue even after doing what @abhishekbaghel and @moonkit suggests.

**Comment by c3n** [comment]
if you're on the same wifi you can run "adb tcpip 5555" to enable tcp-adb, then disconnect the phone from usb and edit /usr/local/lib/python3.6/dist-packages/mvt/android/modules/adb/base.py to import AdbDeviceTcp instead of AdbDeviceUsb and replace the AdbDeviceUsb call with AdbDeviceTcp("ip-of-your-phone",5555).

but unless your android is rooted it doesn't seem to actually do much except complain that "su" is missing. you can also do a backup and check that, but that only seems to check for malicious sms messages

**Comment by botherder** [comment]
> but unless your android is rooted it doesn't seem to actually do much except complain that "su" is missing.

Out of 9 modules, 3 require root privileges.

**Comment by KygekDev** [comment]
> if you're on the same wifi you can run "adb tcpip 5555" to enable tcp-adb, then disconnect the phone from usb and edit /usr/local/lib/python3.6/dist-packages/mvt/android/modules/adb/base.py to import AdbDeviceTcp instead of AdbDeviceUsb and replace the AdbDeviceUsb call with AdbDeviceTcp("ip-of-your-phone",5555).
> 
> but unless your android is rooted it doesn't seem to actually do much except complain that "su" is missing. you can also do a backup and check that, but that only seems to check for malicious sms messages

I got this error when trying to run `mvt-android check-adb`:
```
$ mvt-android check-adb
17:00:09 INFO     [mvt.android.cli] Checking Android through adb bridge
         INFO     [mvt.android.modules.adb.chrome_history] Running module ChromeHistory...
17:00:14 CRITICAL [mvt.android.modules.adb.base] Reading from 192.168.1.5:5555 timed out (5 seconds)
```

My device's IP address was `192.168.1.5`. Also when I ran `adb devices`, my device was listed:
```
$ adb devices
List of devices attached
192.168.1.5:5555        device
```

**Comment by botherder** [comment]
For users running on Windows, it's probably best to use the TCP transport when connecting, for example:
```
$ adb tcpip 5555
$ mvt-android check-adb --serial 192.168.1.20:555
```
Replacing the IP address with the actual IP of the Android device.

Closing this for the time being, until there is more clarity on how to resolve issues with adb-shell and libusb on Windows.
