### ISSUE TITLE
Error when running mvt-ios check-backup or check-iocs with pegasus.stix2

### ISSUE THREAD

**Issue by remtcsdev** [mvt-project/mvt#127]
Hello, I'm trying to run mvt against an iOS backup using pegasus.stix2, but am getting the following error.  Mvt runs fine without specifying pegasus.stix2.  I get the same error on check-backup as well as check-iocs.

```
20:42:36 INFO     [mvt.ios.cli] Checking iTunes backup located at: /home/user/iosbackup/backup/
         INFO     [mvt.ios.cli] Loading indicators from provided file at: /home/user/iosbackup/pegasus.stix2
Traceback (most recent call last):
  File "/home/user/.local/bin/mvt-ios", line 8, in <module>
    sys.exit(cli())
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/mvt/ios/cli.py", line 87, in check_backup
    indicators = Indicators(iocs)
  File "/home/user/.local/lib/python3.8/site-packages/mvt/common/indicators.py", line 19, in __init__
    self.data = json.load(handle)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)

```
pip list
```
Package                Version
---------------------- --------------------
adb-shell              0.4.0
attrs                  19.3.0
Automat                0.8.0
biplist                1.0.3
blinker                1.4
certifi                2019.11.28
chardet                3.0.4
charset-normalizer     2.0.3
click                  8.0.1
cloud-init             21.2
colorama               0.4.3
command-not-found      0.3
commonmark             0.9.1
configobj              5.0.6
constantly             15.1.0
cryptography           2.8
dbus-python            1.2.16
distro                 1.4.0
distro-info            0.23ubuntu1
entrypoints            0.3
httplib2               0.14.0
hyperlink              19.0.0
idna                   2.8
importlib-metadata     1.5.0
incremental            16.10.1
iOSbackup              0.9.912
Jinja2                 2.10.1
jsonpatch              1.22
jsonpointer            2.0
jsonschema             3.2.0
keyring                18.0.1
language-selector      0.1
launchpadlib           1.10.13
lazr.restfulclient     0.14.2
lazr.uri               1.0.3
libusb1                1.9.3
MarkupSafe             1.1.0
more-itertools         4.2.0
mvt                    1.0.13
netifaces              0.10.4
oauthlib               3.1.0
pexpect                4.6.0
pip                    20.0.2
pyasn1                 0.4.2
pyasn1-modules         0.2.1
pycryptodome           3.10.1
Pygments               2.9.0
PyGObject              3.36.0
PyHamcrest             1.9.0
PyJWT                  1.7.1
pymacaroons            0.13.0
PyNaCl                 1.3.0
pyOpenSSL              19.0.0
pyrsistent             0.15.5
pyserial               3.4
python-apt             2.0.0+ubuntu0.20.4.5
python-debian          0.1.36ubuntu1
PyYAML                 5.3.1
requests               2.26.0
requests-unixsocket    0.2.0
rich                   10.6.0
rsa                    4.7.2
SecretStorage          2.3.1
service-identity       18.1.0
setuptools             45.2.0
simplejson             3.17.3
six                    1.14.0
sos                    4.1
ssh-import-id          5.10
systemd-python         234
tld                    0.12.6
tqdm                   4.61.2
Twisted                18.9.0
ubuntu-advantage-tools 27.0
ufw                    0.36
unattended-upgrades    0.1
urllib3                1.25.8
wadllib                1.3.3
wheel                  0.34.2
zipp                   1.0.0
zope.interface         4.7.1
```
Thanks in advance!

**Comment by botherder** [comment]
Can you provide the md5sum of your pegasus.stix2 file?

**Comment by remtcsdev** [comment]
Sure thing.  The file I downloaded yesterday is from AmnestyTech/investigations/2021-07-18_nso, dated 19 July, and the md5 sum is:

`F98584808996AB5A6D96074B4E77F084`

Oddly enough, I just now downloaded the file again from the same location and got a different md5sum:

`6463C1FC774865890AA3637C01EB7401`

It resulted in the same error however.

**Comment by andrew-stclair** [comment]
for what it's worth, i downloaded it and it worked just fine for me

MD5sum: `5a9c24824ddfc35dc345a302edb7a433  pegasus.stix2`

**Comment by remtcsdev** [comment]
To be sure, I just built a fresh VM with Ubuntu 20.04.2 LTS (Server), followed the instructions verbatim, wget a fresh copy of pegasus.stix2, and got the same exact error as above.

**Comment by U039b** [comment]
Are you downloading the STIX file with this URL `https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/pegasus.stix2`?

**Comment by remtcsdev** [comment]
Ok, I'm an idiot.  I was grabbing it from this URL.
`https://github.com/AmnestyTech/investigations/blob/master/2021-07-18_nso/pegasus.stix2`
Grabbing the correct file has resulted in the desired behavior.  Thank you!
