### ISSUE TITLE
mvt-ios check-backup: InteractionC: no such table: ZINTERACTIONS

### ISSUE THREAD

**Issue by dkg** [mvt-project/mvt#142]
When running `mvt-ios check-backup` I ran into this error:

```
  INFO     [mvt.ios.modules.fs.interactionc] Running module InteractionC...                 
  INFO     [mvt.ios.modules.fs.interactionc] Database at path                               
           /home/USER/data/mvt/decrypted/1f/1f5a521220a3ad80ebfdc196978df8e7a2e49dee is    
           malformed. Trying to recover...                                                  
  INFO     [mvt.ios.modules.fs.interactionc] Database at path                               
           /home/USER/data/mvt/decrypted/1f/1f5a521220a3ad80ebfdc196978df8e7a2e49dee       
           recovered successfully!                                                          
  INFO     [mvt.ios.modules.fs.interactionc] Found InteractionC database at path:           
           /home/USER/data/mvt/decrypted/1f/1f5a521220a3ad80ebfdc196978df8e7a2e49dee       
  ERROR    [mvt.ios.modules.fs.interactionc] Error in running extraction from module InteractionC: no such table: ZINTERACTIONS                                       
           Traceback (most recent call last):                                               
             File "/home/USER/.local/lib/python3.9/site-packages/mvt/common/module.py", line 147, in run_module                                                          
               module.run()                                                                 
             File "/home/USER/.local/lib/python3.9/site-packages/mvt/ios/modules/fs/interactionc.py", line 76, in run                                                       
               cur.execute("""                                                              
           sqlite3.OperationalError: no such table: ZINTERACTIONS                           
```

Indeed, the recovered database doesn't have any table in it at all:

```console
USER@HOST:~/data/mvt$ file /home/USER/data/mvt/decrypted/1f/1f5a521220a3ad80ebfdc196978df8e7a2e49dee
/home/USER/data/mvt/decrypted/1f/1f5a521220a3ad80ebfdc196978df8e7a2e49dee: SQLite 3.x database, last written using SQLite version 3034001
USER@HOST:~/data/mvt$ echo .schema | sqlite3 /home/USER/data/mvt/decrypted/1f/1f5a521220a3ad80ebfdc196978df8e7a2e49dee
USER@HOST:~/data/mvt$ ls -l /home/USER/data/mvt/decrypted/1f/1f5a521220a3ad80ebfdc196978df8e7a2e49dee
-rw-r--r-- 1 USER USER 4096 Jul 30 11:47 /home/USER/data/mvt/decrypted/1f/1f5a521220a3ad80ebfdc196978df8e7a2e49dee
USER@HOST:~/data/mvt$ 
```

Happy to try to provide more information if it'd be useful, but it may also be that the best solution is to just handle this error more gracefully (e.g. as though the table was empty and not just missing).

I note that it did need to recover the database first, before finding it was empty, but i also don't know why or how it was corrupt originally.

**Comment by botherder** [comment]
I am not sure why sometimes certain DBs are empty files, but it happens. Currently all generic exceptions are handled here https://github.com/mvt-project/mvt/blob/main/mvt/common/module.py#L156 and purposefully logged the traceback. Do you think that is too noisy? Being an unforeseen anomaly, I think it's nice for users to be able to share logs just like you did, but maybe fully logging a traceback is too alarming?

**Comment by Te-k** [comment]
I am closing this issue as we have not continue this discussion since last summer, feel free to reopen it @dkg if you have some improvements in mind.
