### ISSUE TITLE
mvt-ios decrypt-backup: noisy error message (from iOSbackup.__del__) after error

### ISSUE THREAD

**Issue by dkg** [mvt-project/mvt#150]
When `mvt-ios decrypt-backup` fails for a legitimate reason (like the backup path is wrong, or the password was incorrect), the good error reporting (typically from `log.critical`) gets swamped by a flood of error messages that come afterward, due to the destructor of the `iOSbackup` object.

I think what's happening is that the iOSbackup object is not fully-formed (because the decryption was unsuccessful), and so its destructor fails.  It's possible that this is an issue with the `iOSbackup` module (i've got `iOSbackup` 0.9.912 installed), and should be fixed there.  I'm not sure how to fix it in `mvt` itself, but if you want to suggest an approach, i'm happy to try to implement it.

If you think it should be reported on https://github.com/avibrazil/iOSbackup instead, let me know.  i can open an issue there and point it back to this report.

```console
USER@HOST:~/data/mvt$ mvt-ios decrypt-backup -d xxx /home/USER/data/mvt/bkup/UDID/
11:43:43 INFO     [mvt.ios.cli] Using password from MVT_IOS_BACKUP_PASSWORD environment variable                                                                                                  
         INFO     [mvt.ios.decrypt] Decrypting iOS backup at path /home/USER/data/mvt/bkup/UDID/ with password                                                              
[…]          
         CRITICAL [mvt.ios.decrypt] Failed to decrypt backup. Did you provide the correct password?                                                                                               
Exception ignored in: <function iOSbackup.__del__ at 0x7f5c77c549d0>
Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.9/site-packages/iOSbackup/__init__.py", line 132, in __del__
    self.close()
  File "/home/USER/.local/lib/python3.9/site-packages/iOSbackup/__init__.py", line 138, in close
    os.remove(self.manifestDB)
TypeError: remove: path should be string, bytes or os.PathLike, not NoneType
Traceback (most recent call last):
  File "/home/USER/.local/bin/mvt-ios", line 8, in <module>
    sys.exit(cli())
  File "/home/USER/.local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/USER/.local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/USER/.local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/USER/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/USER/.local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/USER/.local/lib/python3.9/site-packages/mvt/ios/cli.py", line 78, in decrypt_backup
    backup.process_backup()
  File "/home/USER/.local/lib/python3.9/site-packages/mvt/ios/decrypt.py", line 37, in process_backup
    self._backup.getManifestDB()
AttributeError: 'NoneType' object has no attribute 'getManifestDB'
USER@HOST:~/data/mvt$
```

(this is independent of the error message cleanup in #147, fwiw)

**Comment by botherder** [comment]
This looks like the backup wasn't fully completed and it is missing the `Manifest.db` file. Can you check you actually have it in the backup you are testing?

**Comment by botherder** [comment]
Is this error happening only with a particular backup? Does that backup look properly completed (e.g. Manifest.db, Manifest.plist, Status.plist, etc. files are all present)?

Unfortunately iOSbackup has a lot of error handling issues, but the development seems to be stagnant. I think it might be worth reporting, but if, as I suspect, it will get no answer I fear a fork might be needed.

**Comment by dkg** [comment]
This only happens *when there's an error* -- i've seen it when i've supplied the wrong backup password, or when i've failed to specify the path correctly.

The reason i reported this is that i want the error handling cleanup i submitted in #147 to be visible to other novice users like me -- but if this destructor is so noisy, the nice clean error messages are easy to lose in the flood.

Digging a bit deeper, i see simple fixes like https://github.com/avibrazil/iOSbackup/pull/7 on `iOSbackup` upstream haven't been applied yet, which makes me think this is likely an issue with iOSbackup.  I'll submit a fix up there, and link to it here.  If a fork of iOSbackup is needed, whoever forks it can collect the cleanup from that tracker.

**Comment by botherder** [comment]
I'd say let's give some reasonable time to upstream to see if they are actively maintaining the project. After which I guess we can set up a fork on this GitHub org.

**Comment by botherder** [comment]
The PR has been merged and should be fixed in the latest iOSbackup release. Closing this for now.
