### ISSUE TITLE
Android: possible AttributeError during logging

### ISSUE THREAD

**Issue by haskokristof** [mvt-project/mvt#157]
Hi! 

I got the following error during check-adb on android:

```
mint@mint:~$ mvt-android check-adb
15:05:25 INFO     [mvt.android.cli] Checking Android through adb bridge         
         INFO     [mvt.android.modules.adb.chrome_history] Running module       
                  ChromeHistory...                                              
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.8/site-packages/mvt/common/module.py", line 152, in run_module
    module.run()
  File "/home/mint/.local/lib/python3.8/site-packages/mvt/android/modules/adb/chrome_history.py", line 70, in run
    self._adb_process_file(os.path.join("/", CHROME_HISTORY_PATH),
  File "/home/mint/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 184, in _adb_process_file
    self._adb_root_or_die()
  File "/home/mint/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 108, in _adb_root_or_die
    raise InsufficientPrivileges("The Android device does not seem to have a `su` binary. Cannot run this module.")
mvt.common.module.InsufficientPrivileges: The Android device does not seem to have a `su` binary. Cannot run this module.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mvt-android", line 8, in <module>
    sys.exit(cli())
  File "/home/mint/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/mint/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/mint/.local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mint/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mint/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/mint/.local/lib/python3.8/site-packages/mvt/android/cli.py", line 127, in check_adb
    run_module(m)
  File "/home/mint/.local/lib/python3.8/site-packages/mvt/common/module.py", line 157, in run_module
    module.log.info("Insufficient privileges for module %s: %s", module.__class.__name__, e)
AttributeError: 'ChromeHistory' object has no attribute '__class'

```

Looks like that the issue is with mvt/mvt/common/module.py line 157, because the module.__class is missing. 
Its weird, for me because the same attribute is called on line 149.
I'd love to fix it, but I'm not that great with python and I have no IDE installed.

**Comment by botherder** [comment]
Thank you, fixed.

**Comment by haskokristof** [comment]
Thank you for participating in a project like this!

**Comment by sandeep383** [comment]
How was this fixed ? Any hints please.

**Comment by botherder** [comment]
Upgrade to latest version.
