### ISSUE TITLE
Check output folder when running mvt-android download-apks

### ISSUE THREAD

**Issue by UltraHQ** [mvt-project/mvt#158]
`root@debian:~# mvt-android download-apks
19:49:49 INFO     [mvt.android.download_apks] Retrieving package names ...
19:49:50 INFO     [mvt.android.download_apks] There are 536 packages installed on the device. I selected 455 for inspection.
         INFO     [mvt.android.download_apks] Starting extraction of installed APKs at folder None
Traceback (most recent call last):
  File "/usr/local/bin/mvt-android", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mvt/android/cli.py", line 67, in download_apks
    download.run()
  File "/usr/local/lib/python3.7/dist-packages/mvt/android/download_apks.py", line 212, in run
    self.pull_packages()
  File "/usr/local/lib/python3.7/dist-packages/mvt/android/download_apks.py", line 155, in pull_packages
    if not os.path.exists(self.output_folder):
  File "/usr/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType`

Here a picture of it (because of github formatting)
![image](https://user-images.githubusercontent.com/35925402/128609595-b033301f-a66d-4be1-808c-b0a33475e2b0.png)

Running on Debian, arm64-v8a (basically a raspberry pi)
Phone is also rooted

**Comment by UltraHQ** [comment]
Nevermind, I used it wrong, I should've specified where to output.
I'm not sure, but I think it's not written in the usage.

**Comment by botherder** [comment]
Reopening cause this should be handled more gracefully.
