### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by thelacesz** [mvt-project/mvt#163]
Hello dear Developer's,

I made a password backup of my iPhone. but when I want to check the decrypted files, I get the following error:

`root@dev:/home/dev# mvt-ios check-backup --iocs /home/dev/pegasus.stix2 --output /mnt/c/Users/dev/Desktop/eredmeny/ /mnt/c/Users/dev/Desktop/dekodolt/
11:02:30 INFO     [mvt.ios.cli] Checking iTunes backup located at: /mnt/c/Users/dev/Desktop/dekodolt/
         INFO     [mvt.ios.cli] Loading indicators from provided file at: /home/dev/pegasus.stix2
Traceback (most recent call last):
  File "/usr/local/bin/mvt-ios", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mvt/ios/cli.py", line 143, in check_backup
    indicators = Indicators(iocs)
  File "/usr/local/lib/python3.8/dist-packages/mvt/common/indicators.py", line 20, in __init__
    self.data = json.load(handle)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)`

what could be wrong? or am i doing something wrong? I look forward to your reply

Regards
Laszlo

**Comment by botherder** [comment]
Looks like the STIX2 file you downloaded is not valid. Make sure you downloaded it correctly.

**Comment by botherder** [comment]
Catching this more gracefully with 8a91e64bb999b2f727cbe51f9d6087931b4a3f71.
