### ISSUE TITLE
MVT-Android on Windows via WSL (Debian)

### ISSUE THREAD

**Issue by Sebastian-Cerga** [mvt-project/mvt#164]
Hi,

I'm not familar with Python, but I think there might be an easy fix for running MVT on Windows 10+ using any of the WSL distros (in my case I tried Debian), enspecially when on the same network.

You can run adb (in my case 1.0.41) on Windows main machine in tcpip mode i.e.:
`adb tcpip 5555`

Then check what IP your phone has on the local WiFi.. probably something like 192.168.1.20.

Then on the WSL VM run:
`adb connect 192.168.1.20:5555`

And you now have indirect access from WSL 2 to the phone.

Unfortunately one Python script seems to check some USB conditions which are no longer applicable when connecting this way.

See output from my example (username "seb"):

```
mvt-android download-apks --output /mnt/c/Pegasus --all-checks
Traceback (most recent call last):
  File "/home/seb/.local/lib/python3.7/site-packages/adb_shell/transport/usb_transport.py", line 597, in _find_first
    return next(cls._find_devices(setting_matcher, device_matcher=device_matcher, usb_info=usb_info, default_transport_timeout_s=default_transport_timeout_s))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seb/.local/bin/mvt-android", line 10, in <module>
    sys.exit(cli())
  File "/home/seb/.local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/seb/.local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/seb/.local/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/seb/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/seb/.local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/seb/.local/lib/python3.7/site-packages/mvt/android/cli.py", line 67, in download_apks
    download.run()
  File "/home/seb/.local/lib/python3.7/site-packages/mvt/android/download_apks.py", line 210, in run
    self._adb_connect()
  File "/home/seb/.local/lib/python3.7/site-packages/mvt/android/modules/adb/base.py", line 62, in _adb_connect
    self.device = AdbDeviceUsb()
  File "/home/seb/.local/lib/python3.7/site-packages/adb_shell/adb_device.py", line 1500, in __init__
    transport = UsbTransport.find_adb(serial, port_path, default_transport_timeout_s)
  File "/home/seb/.local/lib/python3.7/site-packages/adb_shell/transport/usb_transport.py", line 624, in find_adb
    default_transport_timeout_s=default_transport_timeout_s
  File "/home/seb/.local/lib/python3.7/site-packages/adb_shell/transport/usb_transport.py", line 507, in _find
    return cls._find_first(setting_matcher, device_matcher, usb_info=usb_info, default_transport_timeout_s=default_transport_timeout_s)
  File "/home/seb/.local/lib/python3.7/site-packages/adb_shell/transport/usb_transport.py", line 599, in _find_first
    raise exceptions.UsbDeviceNotFoundError('No device available, or it is in the wrong configuration.')
adb_shell.exceptions.UsbDeviceNotFoundError: No device available, or it is in the wrong configuration.
```

Hope this helps in making the MVT tool available to more people which might not be familiar with Linux or Mac OSs.

**Comment by botherder** [comment]
Can you try now upgrading `pip3 install -U mvt` and specifying `--serial 192.168.1.20:5555` to the mvt command? FWIW, I think the adb connect command might not be necessary.

**Comment by Sebastian-Cerga** [comment]
Works (I used the adb connect command as well). It is now downloading the apks. Thank you.
