### ISSUE TITLE
Docker: No such file or directory: '/root/.android/adbkey'

### ISSUE THREAD

**Issue by vdjiguir** [mvt-project/mvt#165]
Followed instructions using Docker container with no issues.
Started Docker using `docker run -it --privileged -v /dev/bus/usb:/dev/bus/usb mvt` and running it using USB debugging enabled on my Galaxy S20.  
The only step that didn't happen as per instructions is this:
_If this is the first time you connect to this device, you will need to approve the authentication keys through a prompt that will appear on your Android device._

If I run `mvt-android download-apks --output /mvt` I got the following error: 
```
Traceback (most recent call last):
  File "/usr/local/bin/mvt-android", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mvt/android/cli.py", line 70, in download_apks
    download.run()
  File "/usr/local/lib/python3.8/dist-packages/mvt/android/download_apks.py", line 210, in run
    self._adb_connect()
  File "/usr/local/lib/python3.8/dist-packages/mvt/android/modules/adb/base.py", line 51, in _adb_connect
    self._adb_check_keys()
  File "/usr/local/lib/python3.8/dist-packages/mvt/android/modules/adb/base.py", line 43, in _adb_check_keys
    keygen(ADB_KEY_PATH)
  File "/usr/local/lib/python3.8/dist-packages/adb_shell/auth/keygen.py", line 248, in keygen
    with open(filepath, 'wb') as private_key_file:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.android/adbkey'
```

**Comment by samyxdev** [comment]
Can you perform an Adb check? I got the same issue before manually installing platform-tools (you may find other opened issue proposing to include those tools in the docker image, which might not be the case for now).

**Comment by TomaszMyszak** [comment]
enyone have solusion for that?

**Comment by vdjiguir** [comment]
> Can you perform an Adb check using `mvt-android adb-check`?
> 
> I got the same issue before manually installing platform-tools (you may find other open issues proposing to include those tools in the docker image, which might **not be the case for now**).

Same thing
```
# mvt-android check-adb
15:42:22 INFO     [mvt.android.cli] Checking Android through adb bridge
         INFO     [mvt.android.modules.adb.chrome_history] Running module ChromeHistory...
         ERROR    [mvt.android.modules.adb.chrome_history] Error in running extraction from module ChromeHistory: [Errno
                  2] No such file or directory: '/root/.android/adbkey'
                  Traceback (most recent call last):
                    File "/usr/local/lib/python3.8/dist-packages/mvt/common/module.py", line 152, in run_module
                      module.run()
                    File "/usr/local/lib/python3.8/dist-packages/mvt/android/modules/adb/chrome_history.py", line 70, in
                  run
                      self._adb_process_file(os.path.join("/", CHROME_HISTORY_PATH),
                    File "/usr/local/lib/python3.8/dist-packages/mvt/android/modules/adb/base.py", line 189, in
                  _adb_process_file
                      self._adb_connect()
                    File "/usr/local/lib/python3.8/dist-packages/mvt/android/modules/adb/base.py", line 51, in
                  _adb_connect
                      self._adb_check_keys()
                    File "/usr/local/lib/python3.8/dist-packages/mvt/android/modules/adb/base.py", line 43, in
                  _adb_check_keys
                      keygen(ADB_KEY_PATH)
                    File "/usr/local/lib/python3.8/dist-packages/adb_shell/auth/keygen.py", line 248, in keygen
                      with open(filepath, 'wb') as private_key_file:
                  FileNotFoundError: [Errno 2] No such file or directory: '/root/.android/adbkey'
```

**Comment by botherder** [comment]
FWIW, adb generates authentication keys at that path when you use it for the first time or by launching `adb keygen`. I'm not familiar with Docker, so I'm leaving this open for others who contributed the Dockerfile, but I suppose it should just be a matter of adding that command.

**Comment by arky** [comment]
@TomaszMyszak  Check if adding '`mkdir /root/.android`' solves the issue. 

You can force the keygen with '`adb keygen .android/adbkey`' as well.
