### ISSUE TITLE
"plistlib.InvalidFileException: Invalid file" error loops forever

### ISSUE THREAD

**Issue by mailinglists35** [mvt-project/mvt#171]
it runs ok for a rsync filesystem copy with check-fs but fails with check-backup after successfully decrypting an itunes backup 

````
         INFO     [mvt.ios.modules.backup.backup_info] The BackupInfo module does not support checking for indicators
         INFO     [mvt.ios.modules.backup.configuration_profiles] Running module ConfigurationProfiles...
         INFO     [mvt.ios.modules.backup.configuration_profiles] Extracted details about 11 configuration profiles
         INFO     [mvt.ios.modules.backup.configuration_profiles] The ConfigurationProfiles module does not support checking for indicators
         INFO     [mvt.ios.modules.backup.manifest] Running module Manifest...
         INFO     [mvt.ios.modules.backup.manifest] Found Manifest.db database at path: /srv/temp/mvt/Manifest.db
         ERROR    [mvt.ios.modules.backup.manifest] Error reading manifest file metadata
                  Traceback (most recent call last):
                    File "/usr/local/lib/python3.6/dist-packages/mvt/ios/modules/backup/manifest.py", line 118, in run
                      file_plist = plistlib.load(io.BytesIO(file_data["file"]))
                    File "/usr/lib/python3.6/plistlib.py", line 1015, in load
                      return p.parse(fp)
                    File "/usr/lib/python3.6/plistlib.py", line 626, in parse
                      return self._read_object(top_object)
                    File "/usr/lib/python3.6/plistlib.py", line 741, in _read_object
                      result[self._read_object(k)] = self._read_object(o)
                    File "/usr/lib/python3.6/plistlib.py", line 741, in _read_object
                      result[self._read_object(k)] = self._read_object(o)
                    File "/usr/lib/python3.6/plistlib.py", line 744, in _read_object
                      raise InvalidFileException()
                  plistlib.InvalidFileException: Invalid file

````

**Comment by mailinglists35** [comment]
````
# file /srv/temp/mvt/Manifest.db
/srv/temp/mvt/Manifest.db: SQLite 3.x database, user version 2, last written using SQLite version 3028000
````

**Comment by mailinglists35** [comment]
````
sqlite> .schema
CREATE TABLE Files (fileID TEXT PRIMARY KEY, domain TEXT, relativePath TEXT, flags INTEGER, file BLOB);
CREATE INDEX FilesDomainIdx ON Files(domain);
CREATE INDEX FilesRelativePathIdx ON Files(relativePath);
CREATE INDEX FilesFlagsIdx ON Files(flags);
CREATE TABLE Properties (key TEXT PRIMARY KEY, value BLOB);

````

**Comment by mailinglists35** [comment]
select on files shows lots of entries like this

````
SysSharedContainerDomain-systemgroup.com.apple.icloud.ifccd||2
SysSharedContainerDomain-systemgroup.com.apple.icloud.ifccd|Library|2
AppDomainPlugin-com.apple.DocumentsApp.widget||2
AppDomainPlugin-com.apple.DocumentsApp.widget|Library|2
AppDomainPlugin-com.apple.DocumentsApp.widget|Library/Preferences|2
AppDomainPlugin-com.apple.DocumentsApp.widget|Documents|2
AppDomain-com.apple.StoreDemoViewService||2
AppDomain-com.apple.StoreDemoViewService|Library|2
AppDomain-com.apple.StoreDemoViewService|Library/Preferences|2
AppDomain-com.apple.StoreDemoViewService|Documents|2
````

**Comment by botherder** [comment]
Can you try to update from Git and re-run?

**Comment by mailinglists35** [comment]
I've done `pip3 install --upgrade git+git://github.com/mvt-project/mvt.git@main`[1] but still get the same loop. have I done the update correctly? sorry not a pip/python user, just a copy-paste setup instructions monkey, originally installed with `pip3 install mvt`

[1]
````
# pip3 install --upgrade git+git://github.com/mvt-project/mvt.git@main
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Collecting git+git://github.com/mvt-project/mvt.git@main
  Cloning git://github.com/mvt-project/mvt.git (to revision main) to /tmp/pip-req-build-b4c_nh72
  Running command git clone -q git://github.com/mvt-project/mvt.git /tmp/pip-req-build-b4c_nh72
  Resolved git://github.com/mvt-project/mvt.git to commit 67d8820cc99477a249f242bebf580f30557955fe
Requirement already satisfied: click>=8.0.1 in /usr/local/lib/python3.6/dist-packages (from mvt==1.2.1) (8.0.1)
Requirement already satisfied: rich>=10.6.0 in /usr/local/lib/python3.6/dist-packages (from mvt==1.2.1) (10.7.0)
Requirement already satisfied: tld>=0.12.6 in /usr/local/lib/python3.6/dist-packages (from mvt==1.2.1) (0.12.6)
Requirement already satisfied: tqdm>=4.61.2 in /usr/local/lib/python3.6/dist-packages (from mvt==1.2.1) (4.62.1)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.6/dist-packages (from mvt==1.2.1) (2.26.0)
Requirement already satisfied: simplejson>=3.17.3 in /usr/local/lib/python3.6/dist-packages (from mvt==1.2.1) (3.17.3)
Requirement already satisfied: iOSbackup>=0.9.912 in /usr/local/lib/python3.6/dist-packages (from mvt==1.2.1) (0.9.912)
Requirement already satisfied: adb-shell>=0.4.0 in /usr/local/lib/python3.6/dist-packages (from mvt==1.2.1) (0.4.0)
Requirement already satisfied: libusb1>=1.9.3 in /usr/local/lib/python3.6/dist-packages (from mvt==1.2.1) (1.9.3)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from adb-shell>=0.4.0->mvt==1.2.1) (2.1.4)
Requirement already satisfied: rsa in /usr/local/lib/python3.6/dist-packages (from adb-shell>=0.4.0->mvt==1.2.1) (4.7.2)
Requirement already satisfied: pyasn1 in /usr/lib/python3/dist-packages (from adb-shell>=0.4.0->mvt==1.2.1) (0.4.2)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.6/dist-packages (from click>=8.0.1->mvt==1.2.1) (4.6.4)
Requirement already satisfied: pycryptodome in /usr/local/lib/python3.6/dist-packages (from iOSbackup>=0.9.912->mvt==1.2.1) (3.10.1)
Requirement already satisfied: biplist in /usr/local/lib/python3.6/dist-packages (from iOSbackup>=0.9.912->mvt==1.2.1) (1.0.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.6/dist-packages (from requests>=2.26.0->mvt==1.2.1) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.26.0->mvt==1.2.1) (1.22)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.26.0->mvt==1.2.1) (2.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.26.0->mvt==1.2.1) (2018.1.18)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /usr/local/lib/python3.6/dist-packages (from rich>=10.6.0->mvt==1.2.1) (0.4.4)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /usr/local/lib/python3.6/dist-packages (from rich>=10.6.0->mvt==1.2.1) (0.9.1)
Requirement already satisfied: dataclasses<0.9,>=0.7 in /usr/local/lib/python3.6/dist-packages (from rich>=10.6.0->mvt==1.2.1) (0.8)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /usr/local/lib/python3.6/dist-packages (from rich>=10.6.0->mvt==1.2.1) (2.10.0)
Requirement already satisfied: typing-extensions<4.0.0,>=3.7.4 in /usr/local/lib/python3.6/dist-packages (from rich>=10.6.0->mvt==1.2.1) (3.10.0.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata->click>=8.0.1->mvt==1.2.1) (3.5.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
````

````
         ERROR    [mvt.ios.modules.backup.manifest] Error reading manifest file metadata
                  Traceback (most recent call last):
                    File "/usr/local/lib/python3.6/dist-packages/mvt/ios/modules/backup/manifest.py", line 118, in run
                      file_plist = plistlib.load(io.BytesIO(file_data["file"]))
                    File "/usr/lib/python3.6/plistlib.py", line 1015, in load
                      return p.parse(fp)
                    File "/usr/lib/python3.6/plistlib.py", line 626, in parse
                      return self._read_object(top_object)
                    File "/usr/lib/python3.6/plistlib.py", line 741, in _read_object
                      result[self._read_object(k)] = self._read_object(o)
                    File "/usr/lib/python3.6/plistlib.py", line 741, in _read_object
                      result[self._read_object(k)] = self._read_object(o)
                    File "/usr/lib/python3.6/plistlib.py", line 744, in _read_object
                      raise InvalidFileException()
                  plistlib.InvalidFileException: Invalid file
````

**Comment by whorka** [comment]
Try upgrading Python.

I had this same error using Python 3.7, and I noticed the other reports are using Python 3.6 and 3.7.

After I upgraded to Python 3.8 and reinstalled `mvt`, it works.

```
brew install python@3.8
brew link python@3.8
python3 --version
pip3 install mvt
```

Thank you for providing this invaluable tool!

**Comment by securechicken** [comment]
I met the issue as well, using `mvt-ios check-backup`, with Python 3.7 (no issue with Python >= 3.8.0).
I also narrowed the issue appearance at MVT PIP package 1.1.1: the issue does not exist using MVT 1.1.0 from PIP, even with Python 3.7.

As GitHub releases do not include the 1.1.0 version, I can't tell which commit(s) caused it; but I believe from a quick look at commits for 1.2.0 that this might just be from somwhere when [`manifest.py`moved at `mvt/ios/modules/backup/manifest.py`](https://github.com/mvt-project/mvt/commit/cbdbf41e1ef2d10b882af76380a013cef5d7fcfe#diff-90895454a43dc88729ee992e8ac1a058d7a15399c0dc2a227f2fa4e63ff2a506), combined with possibly (pure hypothesis) more "files" being passed to `plistlib.load` in there. Indeed, [Python doc for `plistlib.load` 3.8](https://docs.python.org/3.8/library/plistlib.html) adds "_Changed in version 3.8: Support added for reading and writing UID tokens in binary plists as used by NSKeyedArchiver and NSKeyedUnarchiver._": this might means some files that are passed by MVT to `plistlib.load` can't be read by plistlib in Python 3.7, but can in Python >= 3.8.

Just for context, Python 3.7 is the highest Python3 version we can get from packages on some widely deployed distribution like Debian 10.x and its derivates.

It does not seem that MVT is actually failing from these issues: I can run `mvt-ios check-backup` till the end with Python 3.7, and get similar results than when running with Python 3.8; but can't tell if they are incomplete or flawed because of these issues.

Just for reference, a full ERROR as I get it from MVT PIP 1.1.1 (errors are more verbose in later MVT versions). These errors really flood STDOUT:
```
ERROR    [mvt.ios.modules.backup.manifest] Error reading manifest file metadata                                
                  Traceback (most recent call last):                                                                    
                    File "/usr/local/lib/python3.7/dist-packages/mvt/ios/modules/backup/manifest.py", line 118, in run  
                      file_plist = plistlib.load(io.BytesIO(file_data["file"]))                                         
                    File "/usr/lib/python3.7/plistlib.py", line 950, in load                                            
                      return p.parse(fp)                                                                                
                    File "/usr/lib/python3.7/plistlib.py", line 561, in parse                                           
                      return self._read_object(top_object)                                                              
                    File "/usr/lib/python3.7/plistlib.py", line 676, in _read_object                                    
                      result[self._read_object(k)] = self._read_object(o)                                               
                    File "/usr/lib/python3.7/plistlib.py", line 676, in _read_object                                    
                      result[self._read_object(k)] = self._read_object(o)                                               
                    File "/usr/lib/python3.7/plistlib.py", line 679, in _read_object                                    
                      raise InvalidFileException()                                                                      
                  plistlib.InvalidFileException: Invalid file  
```

**Comment by itinerant-fox** [comment]
> 
> 
> I met the issue as well, using `mvt-ios check-backup`, with Python 3.7 (no issue with Python >= 3.8.0). I also narrowed the issue appearance at MVT PIP package 1.1.1: the issue does not exist using MVT 1.1.0 from PIP, even with Python 3.7.
> 
> This might have appeared from somwhere when [`manifest.py`moved at `mvt/ios/modules/backup/manifest.py`](https://github.com/mvt-project/mvt/commit/cbdbf41e1ef2d10b882af76380a013cef5d7fcfe#diff-90895454a43dc88729ee992e8ac1a058d7a15399c0dc2a227f2fa4e63ff2a506), combined with possibly (pure hypothesis) more "files" being passed to `plistlib.load` in there. Indeed, [Python doc for `plistlib.load` 3.8](https://docs.python.org/3.8/library/plistlib.html) adds "_Changed in version 3.8: Support added for reading and writing UID tokens in binary plists as used by NSKeyedArchiver and NSKeyedUnarchiver._": this might means some files that are passed by MVT to `plistlib.load` can't be read by plistlib in Python 3.7, but can in Python >= 3.8.
> 
> Just for context, Python 3.7 is the highest Python3 version we can get from packages on some widely deployed distribution like Debian 10.x and its derivates.
> 
> It does not seem that MVT is actually failing from these issues: I can run `mvt-ios check-backup` till the end with Python 3.7, and get similar results than when running with Python 3.8; but can't tell if they are incomplete or flawed because of these issues.
> 
> Just for reference, a full ERROR as I get it from MVT PIP 1.1.1 (errors are more verbose in later MVT versions). These errors really flood STDOUT:
> 
> ```
> ERROR    [mvt.ios.modules.backup.manifest] Error reading manifest file metadata                                
>                   Traceback (most recent call last):                                                                    
>                     File "/usr/local/lib/python3.7/dist-packages/mvt/ios/modules/backup/manifest.py", line 118, in run  
>                       file_plist = plistlib.load(io.BytesIO(file_data["file"]))                                         
>                     File "/usr/lib/python3.7/plistlib.py", line 950, in load                                            
>                       return p.parse(fp)                                                                                
>                     File "/usr/lib/python3.7/plistlib.py", line 561, in parse                                           
>                       return self._read_object(top_object)                                                              
>                     File "/usr/lib/python3.7/plistlib.py", line 676, in _read_object                                    
>                       result[self._read_object(k)] = self._read_object(o)                                               
>                     File "/usr/lib/python3.7/plistlib.py", line 676, in _read_object                                    
>                       result[self._read_object(k)] = self._read_object(o)                                               
>                     File "/usr/lib/python3.7/plistlib.py", line 679, in _read_object                                    
>                       raise InvalidFileException()                                                                      
>                   plistlib.InvalidFileException: Invalid file  
> ```

Can verify that running the same in python 3.6.9 produced the error. Running it in python 3.8 worked.

**Comment by botherder** [comment]
This is the result of a log.exception for when the processing fails, so the traceback is intended behavior. The error is caught and logged in full, although I understand it might look alarming, the simple reason might be that the specific file being processed does not contain a valid plist. If it does, it would be useful if someone could check what's the content of the file which fails (which should be logged).

**Comment by botherder** [comment]
Closing this issue for inactivity.
