### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'check_process'

### ISSUE THREAD

**Issue by bed4-0202** [mvt-project/mvt#189]
I followed the instructions "Run `mvt-ios` on a Backup" from https://docs.mvt.re/en/latest/ios/backup/check.html and got a error. 

I ran: 
```
myusername @ ~/Documents/Github/mvt/dev * main [12] → which mvt-ios 
/usr/local/bin/mvt-ios

myusername @ ~/Documents/Github/mvt/dev * main [10] → mvt-ios check-backup --output mvt-backup-check/ /Users/myusername/Library/Application\ Support/MobileSync/Backup/my-phone-udid
```

Which produced:
```
        MVT - Mobile Verification Toolkit
                https://mvt.re
                Version: 1.2.7


21:06:56 INFO     [mvt.ios.cli] Checking iTunes backup located at: /Users/myusername/Library/Application               
                  Support/MobileSync/Backup/my-phone-udid                                              
         INFO     [mvt.ios.cli] Loaded a total of 0 indicators                                                     
         INFO     [mvt.ios.modules.backup.backup_info] Running module BackupInfo...                                
         INFO     [mvt.ios.modules.backup.backup_info] Build Version: 18H17                                        
         INFO     [mvt.ios.modules.backup.backup_info] Device Name:  iPhone                          
         INFO     [mvt.ios.modules.backup.backup_info] Display Name:  iPhone                         
         INFO     [mvt.ios.modules.backup.backup_info] GUID: my-phone-guid                      
         INFO     [mvt.ios.modules.backup.backup_info] ICCID: my-phone-iccid                                 
         INFO     [mvt.ios.modules.backup.backup_info] IMEI: my-phone-imei           `
... blah blah blah...
         INFO     [mvt.ios.modules.mixed.locationd] Extracted a total of 104 Locationd Clients entries             
Traceback (most recent call last):
  File "/usr/local/bin/mvt-ios", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mvt/ios/cli.py", line 171, in check_backup
    run_module(m)
  File "/usr/local/lib/python3.8/site-packages/mvt/common/module.py", line 170, in run_module
    module.check_indicators()
  File "/usr/local/lib/python3.8/site-packages/mvt/ios/modules/mixed/locationd.py", line 59, in check_indicators
    if self.indicators.check_process(proc_name):
AttributeError: 'NoneType' object has no attribute 'check_process'
```

How resolve?

**Comment by botherder** [comment]
Fixed. Try to update with `pip3 install -U mvt`.
