### ISSUE TITLE
AttributeError while running on android

### ISSUE THREAD

**Issue by TheWiesmin** [mvt-project/mvt#197]
Running `mvt-android download-apks` gives the following:
```py
15:29:51 INFO     [mvt.android.download_apks] Retrieving list of installed packages...
Traceback (most recent call last):
  File "/home/gerard/.local/bin/mvt-android", line 8, in <module>
    sys.exit(cli())
  File "/home/gerard/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/gerard/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/gerard/.local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gerard/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gerard/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/gerard/.local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/gerard/.local/lib/python3.8/site-packages/mvt/android/cli.py", line 81, in download_apks
    download.run()
  File "/home/gerard/.local/lib/python3.8/site-packages/mvt/android/download_apks.py", line 181, in run
    self.get_packages()
  File "/home/gerard/.local/lib/python3.8/site-packages/mvt/android/download_apks.py", line 117, in get_packages
    m.run()
  File "/home/gerard/.local/lib/python3.8/site-packages/mvt/android/modules/adb/packages.py", line 92, in run
    self._adb_connect()
  File "/home/gerard/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 54, in _adb_connect
    self._adb_check_keys()
  File "/home/gerard/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 44, in _adb_check_keys
    os.path.makedirs(os.path.dirname(ADB_KEY_PATH))
AttributeError: module 'posixpath' has no attribute 'makedirs'
```

**Comment by Te-k** [comment]
94a8d9dd914a03d8134f4210165410e97d5dedae should fix that, can you try with the last commit?
