### ISSUE TITLE
AttributeError while running mvt-android check-adb on android 

### ISSUE THREAD

**Issue by rahimthl** [mvt-project/mvt#198]
```
Traceback (most recent call last):
  File "/Users/ce-cyber/Desktop/mvt-main/venv/bin/mvt-android", line 10, in <module>
    sys.exit(cli())
  File "/Users/ce-cyber/Desktop/mvt-main/venv/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ce-cyber/Desktop/mvt-main/venv/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/ce-cyber/Desktop/mvt-main/venv/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ce-cyber/Desktop/mvt-main/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ce-cyber/Desktop/mvt-main/venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ce-cyber/Desktop/mvt-main/venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/ce-cyber/Desktop/mvt-main/venv/lib/python3.8/site-packages/mvt/android/cli.py", line 150, in check_adb
    run_module(m)
  File "/Users/ce-cyber/Desktop/mvt-main/venv/lib/python3.8/site-packages/mvt/common/module.py", line 170, in run_module
    module.check_indicators()
  File "/Users/ce-cyber/Desktop/mvt-main/venv/lib/python3.8/site-packages/mvt/android/modules/adb/packages.py", line 55, in check_indicators
    if result["package_name"] in self.indicators.ioc_app_ids:
AttributeError: 'NoneType' object has no attribute 'ioc_app_ids'
```

**Comment by Te-k** [comment]
Can you share the command you used to create this error?

**Comment by Te-k** [comment]
963d3db51a2221027b4b6d4c2823ba235017148f should fix it, can you try with the last version from github?

**Comment by jmaris** [comment]
Having the same issue !
