### ISSUE TITLE
Error in running extraction from module Packages: list index out of range

### ISSUE THREAD

**Issue by spawnrider** [mvt-project/mvt#201]
Hi, 

I am encountering this issue when running the module Package :
```
        INFO     [mvt.android.modules.adb.packages] Running module Packages...
13:10:41 ERROR    [mvt.android.modules.adb.packages] Error in running extraction from module Packages: list index out of range
                  Traceback (most recent call last):
                    File "/usr/local/lib/python3.8/site-packages/mvt/common/module.py", line 153, in run_module
                      module.run()
                    File "/usr/local/lib/python3.8/site-packages/mvt/android/modules/adb/packages.py", line 117, in run
                      timestamp = dumpsys[0].split("=")[1].strip()
                  IndexError: list index out of range
         INFO     [mvt.android.modules.adb.rootbinaries] Running module RootBinaries...
         INFO     [mvt.android.modules.adb.rootbinaries] The RootBinaries module does not support checking for indicators
         INFO     [mvt.android.modules.adb.logcat] Running module Logcat...
13:10:42 INFO     [mvt.android.modules.adb.logcat] The Logcat module does not support checking for indicators
         INFO     [mvt.android.modules.adb.files] Running module Files...
13:11:02 INFO     [mvt.android.modules.adb.files] The Files module does not support checking for indicators

~ took 54s
```

**Comment by spawnrider** [comment]
Just on more info about this issue. 
I run this command in ADB shell : `pm list packages -U -u -i -f`
Then I had this issue on the com.huawei.androidx package ... 
```
package:/system/app/HwJetPack/HwJetPack.apk=com.huawei.androidx  installer=
Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.huawei.androidx
	at com.android.server.pm.Settings.getInstallerPackageNameLPr(Settings.java:4767)
	at com.android.server.pm.PackageManagerService.getInstallerPackageName(PackageManagerService.java:24498)
	at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:800)
	at com.android.se
```

**Comment by botherder** [comment]
This problem should now be fixed after having removed `-U` from here:
https://github.com/mvt-project/mvt/blob/main/mvt/android/modules/adb/packages.py#L167
