### ISSUE TITLE
Decrypting backup fails at __init__.py, line 1165 in unlockKeys

### ISSUE THREAD

**Issue by floppywhisk** [mvt-project/mvt#217]
```
[mvt.ios.decrypt] Decrypting iOS backup at path ****** with key 
                  file ******                                                                              
         ERROR    [mvt.ios.decrypt] Failed decrypting backup. Try to start over with a clear text decrypting password on parameter "cleartextpassword".       
                  Traceback (most recent call last):                                                                                                          
                    File "/home/***/.local/lib/python3.9/site-packages/mvt/ios/decrypt.py", line 161, in decrypt_with_key_file                              
                      self._backup = iOSbackup(udid=os.path.basename(self.backup_path),                                                                       
                    File "/home/***/.local/lib/python3.9/site-packages/iOSbackup/__init__.py", line 190, in __init__                                        
                      self.unlockKeys()                                                                                                                       
                    File "/home/***/.local/lib/python3.9/site-packages/iOSbackup/__init__.py", line 1165, in unlockKeys                                     
                      raise Exception('Failed decrypting backup. Try to start over with a clear text decrypting password on parameter "cleartextpassword".')  
                  Exception: Failed decrypting backup. Try to start over with a clear text decrypting password on parameter "cleartextpassword".              
         CRITICAL [mvt.ios.decrypt] Failed to decrypt backup. Did you provide the correct key file?
```

Running mvt 1.2.14
on an encrypted iOS 14.7.1 backup
from an iPhone 9,3 (iPhone 7 GSM)

Tried using the cleartext password, but throws the same error. Also, could not extract the key until I commented out line 190 in the mentioned __init__.py file

Any ideas what could be at fault?
Thanks for your attention any way :)

**Comment by jooray** [comment]
Same here, I have iTunes backup, provide correct password and I get this error.

**Comment by Te-k** [comment]
Can you try to extract the key with the latest version? 
Are you sure it was the correct password?

**Comment by botherder** [comment]
Closing for inactivity.
