### ISSUE TITLE
TypeError in android/cli.py

### ISSUE THREAD

**Issue by playertr** [mvt-project/mvt#226]
## Summary
Running `mvt-android check-backup` results in a TypeError in `cli.py` when attempting to evaluate `len(indicators.ioc_count)`. Removing the call to `len` allows execution to continue.

## Expected Behavior
I expect the call to `mvt-android check-backup` to succeed with output such as 
```
14:36:19 INFO     [mvt.android.modules.backup.sms] The SMS module produced no detections!
```

## Current Behavior
Running `mvt-android check-backup` causes the following stacktrace.

```
(mvt) tim@tims-computer:~/mvt$ mvt-android check-backup --iocs ~/stalkerware-indicators/stalkerware.stix2 out


        MVT - Mobile Verification Toolkit
                https://mvt.re
                Version: 1.4.0


14:08:14 INFO     [mvt.android.cli] Checking ADB backup located at: out                              
         INFO     [mvt.android.cli] Parsing STIX2 indicators file at path                            
                  /home/tim/stalkerware-indicators/stalkerware.stix2                                 
         INFO     [mvt.android.cli] Loaded a total of 2415 indicators                                
Traceback (most recent call last):
  File "/home/tim/anaconda3/envs/mvt/bin/mvt-android", line 8, in <module>
    sys.exit(cli())
  File "/home/tim/anaconda3/envs/mvt/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/tim/anaconda3/envs/mvt/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/tim/anaconda3/envs/mvt/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tim/anaconda3/envs/mvt/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tim/anaconda3/envs/mvt/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/tim/anaconda3/envs/mvt/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/tim/anaconda3/envs/mvt/lib/python3.8/site-packages/mvt/android/cli.py", line 210, in check_backup
    if len(indicators.ioc_count) > 0:
TypeError: object of type 'int' has no len()
```

## Possible Solution
Removing the `len` call in `android/cli.py::210`, replacing the line with
```
if indicators.ioc_count > 0:
```
seems to fix the problem. Would you like me to submit a PR?

## Context (Environment)
Ubuntu 18.04, native source install in a conda environment, Commit 8f88f87

**Comment by Te-k** [comment]
Hi,

Thanks for reporting this, it is indeed a bug. Can you try with the last commit?

**Comment by playertr** [comment]
It works with the latest commit, 82b57f1. Thank you!
