### ISSUE TITLE
Using Len() on integer in MVT Android

### ISSUE THREAD

**Issue by anandvenkatanarayanan** [mvt-project/mvt#227]
In the current version, in mvt/android/cli.py, we have the following: 

```python
for module in BACKUP_MODULES:
        m = module(base_folder=backup_path, output_folder=output,
                   log=logging.getLogger(module.__module__))

        if serial:
            m.serial = serial

        if len(indicators.ioc_count) > 0:
            indicators.log = m.log
            m.indicators = indicators

        run_module(m)
```

However running mvt-android check-backup will fail because of this code fragment: 
```python
if len(indicators.ioc_count) > 0:
```
Because in mvt/common/indicators.py, we have this code fragment: 
```python

class Indicators:
    """This class is used to parse indicators from a STIX2 file and provide
    functions to compare extracted artifacts to the indicators.


    """

    def __init__(self, log=None):
        self.log = log
        self.ioc_domains = []
        self.ioc_processes = []
        self.ioc_emails = []
        self.ioc_files = []
        self.ioc_files_sha256 = []
        self.ioc_app_ids = []
        self.ios_profile_ids = []
        self.ioc_count = 0
        self._check_env_variable()
```

Notice that the code fragment where ioc_count is initialized as 0 (int). 
```python
        self.ioc_count = 0
```

Because of this, when you run mvt-android, you get this error. 

```shell
$ mvt-android check-backup -o results --iocs pegasus.stix2 .


        MVT - Mobile Verification Toolkit
                https://mvt.re
                Version: 1.4.0


21:31:38 INFO     [mvt.android.cli] Checking ADB backup located at: .                                                                                         
         INFO     [mvt.android.cli] Parsing STIX2 indicators file at path pegasus.stix2                                                                       
         INFO     [mvt.android.cli] Loaded a total of 1499 indicators                                                                                         
Traceback (most recent call last):
  File "/Users/anandv/pegasus/venv/bin/mvt-android", line 8, in <module>
    sys.exit(cli())
  File "/Users/anandv/pegasus/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/anandv/pegasus/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/anandv/pegasus/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/anandv/pegasus/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/anandv/pegasus/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/anandv/pegasus/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/anandv/pegasus/venv/lib/python3.9/site-packages/mvt/android/cli.py", line 210, in check_backup
    if len(indicators.ioc_count) > 0:
TypeError: object of type 'int' has no len()
```

**Comment by Te-k** [comment]
This should be fixed in the last commit, can you try with it?

**Comment by anandvenkatanarayanan** [comment]
Tried  from git repo. And works.
