### ISSUE TITLE
packages.py IndexError: list index out of range

### ISSUE THREAD

**Issue by teunbruijnen** [mvt-project/mvt#234]
While trying to download apks from a Huawei P30 Pro packages.py ran into an IndexError: list index out of range on line 120 (timestamp) which stopped the application from continuing. Troubleshooting showed that an apk didn't included timestamp or date information causing the IndexError.

**Comment by Te-k** [comment]
Hi,
Could you share the exact error log? Could you also share the result of this package info (`dumpsys package PACKAGE_NAME`), either here or in private to `share@amnesty.tech`? 

Thanks

**Comment by teunbruijnen** [comment]
hi thanks for your comment. Here's the info you requested, error log:

```
┌─[✗]─[pizzatonno@pizza-vmwarevirtualplatform]─[/opt/mvt]
└──╼ $mvt-android download-apks --output /home/pizzatonno/MVT --all-checks


        MVT - Mobile Verification Toolkit
                https://mvt.re
                Version: 1.4.5


19:11:15 INFO     [mvt.android.download_apks] Retrieving list of installed      
                  packages...                                                   
Traceback (most recent call last):
  File "/home/pizzatonno/.local/bin/mvt-android", line 8, in <module>
    sys.exit(cli())
  File "/home/pizzatonno/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pizzatonno/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pizzatonno/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pizzatonno/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pizzatonno/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pizzatonno/.local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pizzatonno/.local/lib/python3.9/site-packages/mvt/android/cli.py", line 84, in download_apks
    download.run()
  File "/home/pizzatonno/.local/lib/python3.9/site-packages/mvt/android/download_apks.py", line 181, in run
    self.get_packages()
  File "/home/pizzatonno/.local/lib/python3.9/site-packages/mvt/android/download_apks.py", line 117, in get_packages
    m.run()
  File "/home/pizzatonno/.local/lib/python3.9/site-packages/mvt/android/modules/adb/packages.py", line 120, in run
    timestamp = dumpsys[0].split("=")[1].strip()
IndexError: list index out of range
```
dumpsys literally gives back `['']`
package_name is `com.huawei.androidx`

**Comment by kpcyrd** [comment]
@teunbruijnen can you try
```
adb shell pm list packages -U -u -i -f
```
I'm suspecting this is related to #211

**Comment by teunbruijnen** [comment]
![adb_error](https://user-images.githubusercontent.com/22060261/150641500-8cfb010e-7d98-4530-911f-af409061e317.png)
@kpcyrd here's the results for that

**Comment by botherder** [comment]
Can you try `adb shell pm list packages -u -i -f` without the `-U`?

**Comment by botherder** [comment]
This should now be fixed. Closing for inactivity.
