### ISSUE TITLE
koodous switch error

### ISSUE THREAD

**Issue by MatejKovacic** [mvt-project/mvt#240]
Hi,

I tried to run: `mvt-android download-apks --from-file adb-filez/apks.json --koodous`, but I get an error:

```

        MVT - Mobile Verification Toolkit
                https://mvt.re
                Version: 1.4.7


19:29:32 INFO     [mvt.android.lookups.koodous] Looking up all extracted files on Koodous (www.koodous.com)                                                             
         INFO     [mvt.android.lookups.koodous] This might take a while...                                                                                              
Looking up 495 packages... ━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━  35% 0:03:44
Traceback (most recent call last):
  File "/home/matej/.local/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/matej/.local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/matej/.local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/matej/.local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matej/.local/bin/mvt-android", line 8, in <module>
    sys.exit(cli())
  File "/home/matej/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/matej/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/matej/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/matej/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/matej/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/matej/.local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/matej/.local/lib/python3.8/site-packages/mvt/android/cli.py", line 95, in download_apks
    koodous_lookup(packages)
  File "/home/matej/.local/lib/python3.8/site-packages/mvt/android/lookups/koodous.py", line 34, in koodous_lookup
    report = res.json()
  File "/home/matej/.local/lib/python3.8/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <html lang="en" class="backgroundsize bgpositionshorthand bgpositionxy bgrepeatround bgrepeatspace bgsizecover borderradius cssanimations csscalc csstransforms supports csstransforms3d csstransitions no-flexboxtweener fontface inlinesvg localstorage multiplebgs preserve3d sessionstorage smil svgclippaths svgfilters svgforeignobject canvas todataurljpeg todataurlpng todataurlwebp no-touch"><head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
   <meta name="description" content="Koodous android malware analysis community">
   <meta name="keywords" content="Koodous, android, malware, analysis, community">
   <title>Koodous - Page not found</title>
   
   <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
   <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
   
</head>

<body>
   <div class="wrapper">
      <div class="abs-center wd-xl">
         <!-- START panel-->
         <div class="text-center mb-xl">
            <div class="text-lg mb-lg">404</div>
            <p class="lead m0">We couldn't find this page.</p>
            <p>The page you are looking for does not exists.</p>
         </div>
         <ul class="list-inline text-center text-sm mb-xl">
            <li><a href="/" class="text-muted">Dashboard</a>
            </li>
            <li class="text-muted">|</li>
            <li><a href="/login" class="text-muted">Login</a>
            </li>
            <li class="text-muted">|</li>
            <li><a href="/register" class="text-muted">Register</a>
            </li>
         </ul>
         <div class="p-lg text-center">
            <span>Koodous &copy; 2022</span>
         </div>
      </div>
   </div>
</body>
</html>: 0

```

**Comment by botherder** [comment]
Does this happen repeatedly? I can not replicate this issue.

**Comment by botherder** [comment]
No this looks like you are having some issues with performing the API request to Koodous API server.

**Comment by Te-k** [comment]
Sounds like it was a problem with your network, I close
