### ISSUE TITLE
Unable to install on Mac 

### ISSUE THREAD

**Issue by Can0103** [mvt-project/mvt#243]
Hello, this is showing up when I try to install:

```
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/cano/mvt/setup.py", line 10, in <module>
          from mvt.common.version import MVT_VERSION
        File "/Users/cano/mvt/mvt/common/version.py", line 6, in <module>
          import requests
      ModuleNotFoundError: No module named 'requests'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by m000lie** [comment]
install requests module via `pip install requests`

**Comment by Te-k** [comment]
Are you using pip to install the package? What command are you using?
