### ISSUE TITLE
Error on Ubuntu trying to download apks

### ISSUE THREAD

**Issue by deimidis** [mvt-project/mvt#284]
Hi, thanks for this tool. We are analyzing some Android phones (Samsung). Backup of sms and dumpsys works fine But when I tried to download apks I had these errors

```
mvt-android download-apks --output apks/


        MVT - Mobile Verification Toolkit
                https://mvt.re
                Version: 1.5.5


14:52:40 INFO     [mvt.android.download_apks] Retrieving list of installed packages...                                                                
14:56:07 INFO     [mvt.android.download_apks] Third-party package "com.whatsapp" requested 11 potentially dangerous permissions                       
         INFO     [mvt.android.download_apks] Third-party package "org.thoughtcrime.securesms" requested 14 potentially dangerous permissions         
         INFO     [mvt.android.download_apks] Found non-system package with name "org.jitsi.meet" installed by "com.android.vending" on 2022-06-18    
                  19:13:51                                                                                                                            
         INFO     [mvt.android.download_apks] Found non-system package with name "com.nextcloud.client" installed by "com.android.vending" on         
                  2022-06-18 02:31:11                                                                                                                 
         INFO     [mvt.android.download_apks] Found non-system package with name "com.ketanolab.nusimi" installed by "com.android.vending" on         
                  2022-06-20 11:26:29                                                                                                                 
         INFO     [mvt.android.download_apks] Found non-system package with name "org.telegram.messenger" installed by "com.android.vending" on       
                  2022-06-20 14:07:22                                                                                                                 
         INFO     [mvt.android.download_apks] Found non-system package with name "com.google.android.apps.docs.editors.docs" installed by             
                  "com.android.vending" on 2022-06-18 04:19:58                                                                                        
         INFO     [mvt.android.download_apks] Found non-system package with name "com.dts.freefireth" installed by "com.android.vending" on 2022-05-28
                  12:03:50                                                                                                                            
         INFO     [mvt.android.download_apks] Found non-system package with name "com.whatsapp" installed by "com.android.vending" on 2022-06-14      
                  15:58:06                                                                                                                            
         INFO     [mvt.android.download_apks] Found non-system package with name "com.google.android.apps.docs.editors.sheets" installed by           
                  "com.android.vending" on 2022-06-18 08:31:09                                                                                        
         INFO     [mvt.android.download_apks] Found non-system package with name "com.google.android.apps.docs.editors.slides" installed by           
                  "com.android.vending" on 2022-06-18 08:12:47                                                                                        
         INFO     [mvt.android.download_apks] Found non-system package with name "com.paypal.android.p2pmobile" installed by "com.android.vending" on 
                  2022-06-11 14:41:08                                                                                                                 
         INFO     [mvt.android.download_apks] Found non-system package with name "com.sec.android.app.voicenote" installed by                         
                  "com.samsung.android.app.omcagent" on 2021-11-04 14:13:22                                                                           
         INFO     [mvt.android.download_apks] Found non-system package with name "se.leap.bitmaskclient" installed by "com.android.vending" on        
                  2022-05-11 00:48:15                                                                                                                 
         INFO     [mvt.android.download_apks] Found non-system package with name "com.mooveit.bcpb" installed by "com.android.vending" on 2022-06-02  
                  09:13:14                                                                                                                            
         INFO     [mvt.android.download_apks] Found non-system package with name "us.zoom.videomeetings" installed by "com.android.vending" on        
                  2022-06-04 11:52:02                                                                                                                 
         INFO     [mvt.android.download_apks] Found non-system package with name "com.instagram.android" installed by "com.android.vending" on        
                  2022-06-22 11:23:12                                                                                                                 
         INFO     [mvt.android.download_apks] Found non-system package with name "com.pinterest" installed by "com.android.vending" on 2022-06-18     
                  09:09:03                                                                                                                            
         INFO     [mvt.android.download_apks] Found non-system package with name "org.thoughtcrime.securesms" installed by "com.android.vending" on   
                  2022-06-08 18:12:04                                                                                                                 
         INFO     [mvt.android.download_apks] Found non-system package with name "com.microsoft.office.outlook" installed by "com.android.vending" on 
                  2022-06-20 14:05:58                                                                                                                 
         INFO     [mvt.android.download_apks] Found non-system package with name "com.google.android.apps.classroom" installed by                     
                  "com.android.vending" on 2022-06-15 12:52:29                                                                                        
         INFO     [mvt.android.download_apks] Found non-system package with name "com.google.android.apps.docs" installed by "com.android.vending" on 
                  2022-06-20 11:26:01                                                                                                                 
         INFO     [mvt.android.download_apks] Found non-system package with name "com.osbolivia.yaigo" installed by "com.android.vending" on          
                  2022-06-20 14:02:25                                                                                                                 
         INFO     [mvt.android.download_apks] Found non-system package with name "com.pedidosya" installed by "com.android.vending" on 2022-06-11     
                  14:47:38                                                                                                                            
         INFO     [mvt.android.download_apks] Found non-system package with name "com.google.android.apps.photos" installed by "com.android.vending"  
                  on 2022-06-20 11:21:35                                                                                                              
         INFO     [mvt.android.download_apks] Found non-system package with name "com.spotify.music" installed by "com.android.vending" on 2022-06-16 
                  00:47:52                                                                                                                            
         INFO     [mvt.android.download_apks] Found non-system package with name "com.microsoft.office.officehubrow" installed by                     
                  "com.android.vending" on 2022-06-04 12:04:06                                                                                        
         INFO     [mvt.android.download_apks] Found non-system package with name "com.Slack" installed by "com.android.vending" on 2022-06-18 08:32:22
         INFO     [mvt.android.download_apks] Found non-system package with name "com.sec.android.app.popupcalculator" installed by                   
                  "com.android.vending" on 2022-05-31 13:35:29                                                                                        
         INFO     [mvt.android.download_apks] Found non-system package with name "org.mozilla.firefox" installed by "com.android.vending" on          
                  2022-06-15 12:53:35                                                                                                                 
         INFO     [mvt.android.download_apks] Found non-system package with name "com.samsung.android.app.notes" installed by                         
                  "com.samsung.android.app.omcagent" on 2021-11-11 18:07:46                                                                           
         INFO     [mvt.android.download_apks] Found non-system package with name "com.google.android.apps.youtube.music" installed by                 
                  "com.android.vending" on 2022-06-15 12:54:14                                                                                        
         INFO     [mvt.android.download_apks] Found non-system package with name "eu.faircode.email" installed by "com.android.vending" on 2022-04-23 
                  13:26:57                                                                                                                            
         INFO     [mvt.android.download_apks] Found non-system package with name "org.openobservatory.ooniprobe" installed by "com.android.vending" on
                  2022-05-19 12:15:01                                                                                                                 
         INFO     [mvt.android.download_apks] Found non-system package with name "com.stremio.one" installed by "com.android.vending" on 2022-06-08   
                  18:13:04                                                                                                                            
         INFO     [mvt.android.download_apks] Found non-system package with name "com.microsoft.teams" installed by "com.android.vending" on          
                  2022-06-20 14:01:02                                                                                                                 
         ERROR    [mvt.android.lookups.virustotal] Unfortunately VirusTotal lookup is disabled until further notice, due to unresolved issues with the
                  API service.                                                                                                                        
         INFO     [mvt.android.lookups.koodous] Looking up all extracted files on Koodous (www.koodous.com)                                           
         INFO     [mvt.android.lookups.koodous] This might take a while...                                                                            
Looking up 34 packages... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
Traceback (most recent call last):
  File "/home/deimidis/.local/lib/python3.10/site-packages/requests/models.py", line 972, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/deimidis/.local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/deimidis/.local/lib/python3.10/site-packages/simplejson/decoder.py", line 373, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
simplejson.errors.JSONDecodeError: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 19)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deimidis/.local/bin/mvt-android", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/deimidis/.local/lib/python3.10/site-packages/mvt/android/cli.py", line 93, in download_apks
    download.run()
  File "/home/deimidis/.local/lib/python3.10/site-packages/mvt/android/download_apks.py", line 181, in run
    self.get_packages()
  File "/home/deimidis/.local/lib/python3.10/site-packages/mvt/android/download_apks.py", line 117, in get_packages
    m.run()
  File "/home/deimidis/.local/lib/python3.10/site-packages/mvt/android/modules/adb/packages.py", line 266, in run
    koodous_lookup(packages_to_lookup)
  File "/home/deimidis/.local/lib/python3.10/site-packages/mvt/android/lookups/koodous.py", line 34, in koodous_lookup
    report = res.json()
  File "/home/deimidis/.local/lib/python3.10/site-packages/requests/models.py", line 976, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 5 (char 4)

```
Which could be the problem?

**Comment by botherder** [comment]
Please check #273.
Closing as duplicate.
