### ISSUE TITLE
mvt-android does nothing

### ISSUE THREAD

**Issue by Azaretdodo** [mvt-project/mvt#302]
hello,

i have install your program using the 'sudo python3 setup.py install' but now if i want use your program this doesn't work,

`:~/programs/mvt$ mvt-android
mvt-android : commande introuvable
`

then i have follow your directory test without success because i have install the dependency but i fall on an error unknown : 

`:~/programs/mvt/tests$ python3 test_check_backup.py 
Traceback (most recent call last):
  File "/home/dorianrosse/programs/mvt/tests/test_check_backup.py", line 10, in <module>
    from .utils import get_ios_backup_folder
ImportError: attempted relative import with no known parent package
`

and a dependencies i can't install : 

`:~/programs/mvt/tests$ python3 test_check_bugreport.py 
Traceback (most recent call last):
  File "/home/dorianrosse/programs/mvt/tests/test_check_bugreport.py", line 10, in <module>
    from mvt.android.cli import check_bugreport
  File "/usr/local/lib/python3.10/site-packages/mvt-2.1.6-py3.10.egg/mvt/android/__init__.py", line 6, in <module>
    from .cli import cli
  File "/usr/local/lib/python3.10/site-packages/mvt-2.1.6-py3.10.egg/mvt/android/cli.py", line 18, in <module>
    from .cmd_check_adb import CmdAndroidCheckADB
  File "/usr/local/lib/python3.10/site-packages/mvt-2.1.6-py3.10.egg/mvt/android/cmd_check_adb.py", line 11, in <module>
    from .modules.adb import ADB_MODULES
  File "/usr/local/lib/python3.10/site-packages/mvt-2.1.6-py3.10.egg/mvt/android/modules/adb/__init__.py", line 6, in <module>
    from .chrome_history import ChromeHistory
  File "/usr/local/lib/python3.10/site-packages/mvt-2.1.6-py3.10.egg/mvt/android/modules/adb/chrome_history.py", line 14, in <module>
    from .base import AndroidExtraction
  File "/usr/local/lib/python3.10/site-packages/mvt-2.1.6-py3.10.egg/mvt/android/modules/adb/base.py", line 22, in <module>
    from usb1 import USBErrorAccess, USBErrorBusy
ModuleNotFoundError: No module named 'usb1'
dorianrosse@Ubuntu-ThinkPad-X250:~/programs/mvt/tests$ pip3 install usb1
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement usb1 (from versions: none)
ERROR: No matching distribution found for usb1
dorianrosse@Ubuntu-ThinkPad-X250:~/programs/mvt/tests$ pip install usb1
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement usb1 (from versions: none)
ERROR: No matching distribution found for usb1
`
again the error unknown : 

`:~/programs/mvt/tests$ python3 conftest.py 
Traceback (most recent call last):
  File "/home/dorianrosse/programs/mvt/tests/conftest.py", line 10, in <module>
    from .artifacts.generate_stix import generate_test_stix_file
ImportError: attempted relative import with no known parent package
`

then i have tried your subdirectories android finaly all asked the module python usb1 also i have tried your module python init without success for the module python missing...

thanks you in advance to repair your github,

Regards.

Azaretdodo.

**Comment by botherder** [comment]
The software is installed using `pip3 install mvt`.
