### ISSUE TITLE
Error by scanning an android backup

### ISSUE THREAD

**Issue by Morp2023** [mvt-project/mvt#334]
Hi there,
i get an error by scanning a backup:
```
Traceback (most recent call last):
  File "/usr/local/bin/mvt-android", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aleapp/.local/lib/python3.10/site-packages/mvt/android/cli.py", line 189, in check_backup
    cmd.run()
  File "/home/aleapp/.local/lib/python3.10/site-packages/mvt/common/command.py", line 199, in run
    self._store_info()
  File "/home/aleapp/.local/lib/python3.10/site-packages/mvt/common/command.py", line 114, in _store_info
    self.generate_hashes()
  File "/home/aleapp/.local/lib/python3.10/site-packages/mvt/common/command.py", line 133, in generate_hashes
    for file in generate_hashes_from_path(self.target_path, self.log):
  File "/home/aleapp/.local/lib/python3.10/site-packages/mvt/common/utils.py", line 186, in generate_hashes_from_path
    sha256 = get_sha256_from_file_path(file_path)
  File "/home/aleapp/.local/lib/python3.10/site-packages/mvt/common/utils.py", line 164, in get_sha256_from_file_path
    with open(file_path, "rb") as handle:
OSError: [Errno 36] File name too long: '/mnt/hgfs/Z/Dump/data/data/com.binance.dev/code_cache/flutter_engine/d3ea636dc5d16b56819f3266241e1f708979c233/skia/5c0eb3eb6dd563d7ca532f74f8c28bd0dbca40bb/HRIAAAAAAAMAAAAAARMPZ72HPQCFR7H7777QGAAAAAAAAAAAIQCQAAACAAAAAZQIAAAAAAAAAAAAAAB
```

**Comment by Te-k** [comment]
Hi,
Thanks for raising this issue. It is fixed with the last commit, however this is a limitation inherent to python and there won't be file hashing in that case.
Let me know if you encounter that issue again.

**Comment by reacan** [comment]
Hello! 

I got the same error when comparing an output of android scan with a stix2 file. mvt version 2.3.0.

mvt-android check-iocs --iocs stix2/quadream_kingspawn.stix2 mvt_15.07.2023

Traceback (most recent call last):
  File "/usr/local/bin/mvt-android", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mvt/android/cli.py", line 338, in check_iocs
    cmd.run()
  File "/usr/local/lib/python3.9/dist-packages/mvt/common/cmd_check_iocs.py", line 65, in run
    m = iocs_module.from_json(
  File "/usr/local/lib/python3.9/dist-packages/mvt/common/module.py", line 73, in from_json
    results = json.load(handle)
  File "/usr/local/lib/python3.9/dist-packages/simplejson/__init__.py", line 452, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/dist-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/dist-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/dist-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

What could be causing this issue? Incompatible python version?
