### ISSUE TITLE
[Solved] Module: ahocorasick in Manjaro (Arch) missing

### ISSUE THREAD

**Issue by gerega** [mvt-project/mvt#376]
Version: mvt 2.4.0-1

Check out the last line:

`$ mvt-android
Traceback (most recent call last):
  File "/usr/bin/mvt-android", line 5, in <module>
    from mvt.android import cli
  File "/usr/lib/python3.11/site-packages/mvt/android/__init__.py", line 6, in <module>
    from .cli import cli
  File "/usr/lib/python3.11/site-packages/mvt/android/cli.py", line 10, in <module>
    from mvt.common.cmd_check_iocs import CmdCheckIOCS
  File "/usr/lib/python3.11/site-packages/mvt/common/cmd_check_iocs.py", line 10, in <module>
    from mvt.common.command import Command
  File "/usr/lib/python3.11/site-packages/mvt/common/command.py", line 13, in <module>
    from mvt.common.indicators import Indicators
  File "/usr/lib/python3.11/site-packages/mvt/common/indicators.py", line 12, in <module>
    import ahocorasick
ModuleNotFoundError: No module named 'ahocorasick'
`
You need to install manually:

`$ yay python-pyahocorasick`

For your information, only!

**Comment by Te-k** [comment]
@kpcyrd : you may be interested by that

**Comment by kpcyrd** [comment]
Thanks for the heads up, I've created a package for python-pyahocorasick, uploaded `mvt-2.4.1-2-any.pkg.tar.zst` with the additional dependency and added a test to ensure `dev/mvt-android --help` and `dev/mvt-ios --help` are working correctly, so this (hopefully) [won't happen again in the future](https://gitlab.archlinux.org/archlinux/packaging/packages/mvt/-/commit/a06edb27d9802bf05ad620f0c437ef240410557d#9b9baac1eb9b72790eef5540a1685306fc43fd6c_25_25).

It might take some time until the package arrives in Manjaro.

**Comment by Te-k** [comment]
Thanks for all the work to package MVT @kpcyrd !
