### ISSUE TITLE
Some apks fail to download

### ISSUE THREAD

**Issue by AntonLydike** [mvt-project/mvt#4]
When running `mvt-android download-apks --output /path/to/folder --all-checks` I get this output on *some* apks (all the juicy preinstalled system ones) :

```
         ERROR    [mvt.android.download_apks] Failed to pull package file from                
                  /vendor/app/CACertService/CACertService.apk: Unable to download file        
                  /vendor/app/CACertService/CACertService.apk: Command failed: open failed:   
                  Permission denied                                                           
                  Traceback (most recent call last):                                          
                    File "/tmp/mvt/mvt/android/modules/adb/base.py", line 121, in             
                  _adb_download                                                               
                      self.device.pull(remote_path, local_path, progress_callback)            
                    File "/run/user/1000/tmp.VgD6fU9ccG/lib/python3.8/site-packages/adb_shell/
                  adb_device.py", line 893, in pull                                           
                      self._pull(device_path, stream, progress_callback, adb_info,            
                  filesync_info)                                                              
                    File "/run/user/1000/tmp.VgD6fU9ccG/lib/python3.8/site-packages/adb_shell/
                  adb_device.py", line 918, in _pull                                          
                      for cmd_id, _, data in self._filesync_read_until([constants.DATA],      
                  [constants.DONE], adb_info, filesync_info):                                 
                    File "/run/user/1000/tmp.VgD6fU9ccG/lib/python3.8/site-packages/adb_shell/
                  adb_device.py", line 1381, in _filesync_read_until                          
                      cmd_id, header, data = self._filesync_read(expected_ids + finish_ids,   
                  adb_info, filesync_info)                                                    
                    File "/run/user/1000/tmp.VgD6fU9ccG/lib/python3.8/site-packages/adb_shell/
                  adb_device.py", line 1320, in _filesync_read                                
                      raise exceptions.AdbCommandFailureException('Command failed:            
                  {}'.format(reason))                                                         
                  adb_shell.exceptions.AdbCommandFailureException: Command failed: open       
                  failed: Permission denied                                                   
                                                                                              
                  During handling of the above exception, another exception occurred:         
                                                                                              
                  Traceback (most recent call last):                                          
                    File "/tmp/mvt/mvt/android/download_apks.py", line 138, in                
                  pull_package_file                                                           
                      self._adb_download(remote_path, local_path,                             
                    File "/tmp/mvt/mvt/android/modules/adb/base.py", line 123, in             
                  _adb_download                                                               
                      raise Exception(f"Unable to download file {remote_path}: {e}")          
                  Exception: Unable to download file                                          
                  /vendor/app/CACertService/CACertService.apk: Command failed: open failed:   
                  Permission denied                                                           
```

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
If it's a non-rooted Android that's a normal result.

**Comment by AntonLydike** [comment]
Ah okay, thanks for the info. Maybe there should be an indicator that you need a rooted android device to do this? Anyway. I'll close this issue.
