### ISSUE TITLE
Error when running check-backup command. I don't see any FAQ guide? I have the latest python3 build and sqlite3. 

### ISSUE THREAD

**Issue by sealvessel** [mvt-project/mvt#402]
MVT - Mobile Verification Toolkit
                https://mvt.re
                Version: 2.4.2
                Indicators updates checked recently, next automatic check in
12 hours

21:32:01 INFO     [mvt.ios.cmd_check_backup] Parsing STIX2 indicators file  
                  at path /Users/o/Library/Application                      
                  Support/mvt/indicators/raw.githubusercontent.com_mvt-proje
                  ct_mvt-indicators_main_intellexa_predator_predator.stix2  
         INFO     [mvt.ios.cmd_check_backup] Parsing STIX2 indicators file  
                  at path /Users/o/Library/Application                      
                  Support/mvt/indicators/raw.githubusercontent.com_mvt-proje
                  ct_mvt-indicators_main_2023-04-11_quadream_kingspawn.stix2
         INFO     [mvt.ios.cmd_check_backup] Parsing STIX2 indicators file  
                  at path /Users/o/Library/Application                      
                  Support/mvt/indicators/raw.githubusercontent.com_mvt-proje
                  ct_mvt-indicators_main_2022-06-23_rcs_lab_rcs.stix2       
         INFO     [mvt.ios.cmd_check_backup] Parsing STIX2 indicators file  
                  at path /Users/o/Library/Application                      
                  Support/mvt/indicators/raw.githubusercontent.com_AssoEchap
                  _stalkerware-indicators_master_generated_stalkerware.stix2
21:32:02 INFO     [mvt.ios.cmd_check_backup] Parsing STIX2 indicators file  
                  at path /Users/o/Library/Application                      
                  Support/mvt/indicators/raw.githubusercontent.com_mvt-proje
                  ct_mvt-indicators_main_2023-07-25_wyrmspy_dragonegg_wyrmsp
                  y_dragonegg.stix2                                         
         INFO     [mvt.ios.cmd_check_backup] Parsing STIX2 indicators file  
                  at path /Users/o/Library/Application                      
                  Support/mvt/indicators/raw.githubusercontent.com_AmnestyTe
                  ch_investigations_master_2021-07-18_nso_pegasus.stix2     
21:32:03 INFO     [mvt.ios.cmd_check_backup] Parsing STIX2 indicators file  
                  at path /Users/o/Library/Application                      
                  Support/mvt/indicators/raw.githubusercontent.com_mvt-proje
                  ct_mvt-indicators_main_2023-06_01_operation_triangulation_
                  operation_triangulation.stix2                             
         INFO     [mvt.ios.cmd_check_backup] Parsing STIX2 indicators file  
                  at path /Users/o/Library/Application                      
                  Support/mvt/indicators/raw.githubusercontent.com_AmnestyTe
                  ch_investigations_master_2023-03-29_android_campaign_malwa
                  re.stix2                                                  
         INFO     [mvt.ios.cmd_check_backup] Loaded a total of 9390 unique  
                  indicators                                                
         INFO     [mvt] Checking iTunes backup located at:                  
                  /Users/o/Library/Application                              
                  Support/MobileSync/Backup/00008110-00127D0102EB801E       
         INFO     [mvt.ios.modules.backup.backup_info] Running module       
                  BackupInfo...                                             
         INFO     [mvt.ios.modules.backup.backup_info] Build Version: 20G81 
         INFO     [mvt.ios.modules.backup.backup_info] Device Name: iPhone  
                  13 Pro Max                                                
         INFO     [mvt.ios.modules.backup.backup_info] Display Name: iPhone 
                  13 Pro Max                                                
         INFO     [mvt.ios.modules.backup.backup_info] GUID:                
                  <placeholder>                          
         INFO     [mvt.ios.modules.backup.backup_info] ICCID:               
                  <placeholder>                                      
         INFO     [mvt.ios.modules.backup.backup_info] IMEI: <placeholder>
         INFO     [mvt.ios.modules.backup.backup_info] MEID: <placeholder> 
         INFO     [mvt.ios.modules.backup.backup_info] Installed            
                  (deleted the apps)  
         INFO     [mvt.ios.modules.backup.backup_info] Last Backup Date:    
                  2023-09-29 13:19:47                                       
         INFO     [mvt.ios.modules.backup.backup_info] Phone Number: +63 999
                  531 6776                                                  
         INFO     [mvt.ios.modules.backup.backup_info] Product Name: iPhone 
                  13 Pro Max                                                
         INFO     [mvt.ios.modules.backup.backup_info] Product Type:        
                  iPhone14,3 (iPhone 13 Pro Max)                            
         INFO     [mvt.ios.modules.backup.backup_info] Product Version:     
                  16.6.1                                                    
         INFO     [mvt.ios.modules.backup.backup_info] Serial Number:       
                  serial                                                
         INFO     [mvt.ios.modules.backup.backup_info] Target Identifier:   
                  deleted target identifier                                 
         INFO     [mvt.ios.modules.backup.backup_info] Target Type: Device  
         INFO     [mvt.ios.modules.backup.backup_info] Unique Identifier:   
                  deleted this too                                 
         INFO     [mvt.ios.modules.backup.backup_info] iTunes Version: None 
         WARNING  [mvt.ios.modules.backup.backup_info] This phone is running
                  an outdated iOS version: 16.6.1 (latest is 17.0.2)        
         INFO     [mvt.ios.modules.backup.backup_info] The BackupInfo module
                  does not support checking for indicators                  
         INFO     [mvt.ios.modules.backup.configuration_profiles] Running   
                  module ConfigurationProfiles...                           
         ERROR    [mvt.ios.modules.backup.configuration_profiles] The       
                  ConfigurationProfiles module database seems to be         
                  corrupted: failed to query Manifest.db: file is not a     
                  database                                                  
         INFO     [mvt.ios.modules.backup.manifest] Running module          
                  Manifest...                                               
         INFO     [mvt.ios.modules.backup.manifest] Found Manifest.db       
                  database at path: /Users/o/Library/Application            
                  Support/MobileSync/Backup/00008110-00127D0102EB801E/Manife
                  st.db                                                     
         ERROR    [mvt.ios.modules.backup.manifest] Error in running        
                  extraction from module Manifest: file is not a database   
                  Traceback (most recent call last):                        
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/module
                  .py", line 167, in run_module                             
                      exec_or_profile("module.run()", globals(), locals())  
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/utils.
                  py", line 236, in exec_or_profile                         
                      exec(module, globals, locals)                         
                    File "<string>", line 1, in <module>                    
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/b
                  ackup/manifest.py", line 130, in run                      
                      cur.execute("SELECT * FROM Files;")                   
                  sqlite3.DatabaseError: file is not a database             
         INFO     [mvt.ios.modules.backup.profile_events] Running module    
                  ProfileEvents...                                          
         ERROR    [mvt.ios.modules.backup.profile_events] The ProfileEvents 
                  module database seems to be corrupted: failed to query    
                  Manifest.db: file is not a database                       
         INFO     [mvt.ios.modules.mixed.calls] Running module Calls...     
         INFO     [mvt.ios.modules.mixed.calls] Found Calls database at     
                  path: /Users/o/Library/Application                        
                  Support/MobileSync/Backup/00008110-00127D0102EB801E/5a/5a4
                  935c78a5255723f707230a451d79c540d2741                     
         ERROR    [mvt.ios.modules.mixed.calls] Error in running extraction 
                  from module Calls: file is not a database                 
                  Traceback (most recent call last):                        
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/module
                  .py", line 167, in run_module                             
                      exec_or_profile("module.run()", globals(), locals())  
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/utils.
                  py", line 236, in exec_or_profile                         
                      exec(module, globals, locals)                         
                    File "<string>", line 1, in <module>                    
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/calls.py", line 58, in run                           
                      cur.execute(                                          
                  sqlite3.DatabaseError: file is not a database             
         INFO     [mvt.ios.modules.mixed.chrome_favicon] Running module     
                  ChromeFavicon...                                          
         INFO     [mvt.ios.modules.mixed.chrome_favicon] There might be no  
                  data to extract by module ChromeFavicon: unable to find   
                  the module's database file                                
         INFO     [mvt.ios.modules.mixed.chrome_history] Running module     
                  ChromeHistory...                                          
         INFO     [mvt.ios.modules.mixed.chrome_history] There might be no  
                  data to extract by module ChromeHistory: unable to find   
                  the module's database file                                
         INFO     [mvt.ios.modules.mixed.contacts] Running module           
                  Contacts...                                               
         INFO     [mvt.ios.modules.mixed.contacts] Found Contacts database  
                  at path: /Users/o/Library/Application                     
                  Support/MobileSync/Backup/00008110-00127D0102EB801E/31/31b
                  b7ba8914766d4ba40d6dfb6113c8b614be442                     
         ERROR    [mvt.ios.modules.mixed.contacts] Error in running         
                  extraction from module Contacts: file is not a database   
                  Traceback (most recent call last):                        
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/module
                  .py", line 167, in run_module                             
                      exec_or_profile("module.run()", globals(), locals())  
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/utils.
                  py", line 236, in exec_or_profile                         
                      exec(module, globals, locals)                         
                    File "<string>", line 1, in <module>                    
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/contacts.py", line 50, in run                        
                      cur.execute(                                          
                  sqlite3.DatabaseError: file is not a database             
         INFO     [mvt.ios.modules.mixed.firefox_favicon] Running module    
                  FirefoxFavicon...                                         
         INFO     [mvt.ios.modules.mixed.firefox_favicon] There might be no 
                  data to extract by module FirefoxFavicon: unable to find  
                  the module's database file                                
         INFO     [mvt.ios.modules.mixed.firefox_history] Running module    
                  FirefoxHistory...                                         
         INFO     [mvt.ios.modules.mixed.firefox_history] There might be no 
                  data to extract by module FirefoxHistory: unable to find  
                  the module's database file                                
         INFO     [mvt.ios.modules.mixed.idstatuscache] Running module      
                  IDStatusCache...                                          
         INFO     [mvt.ios.modules.mixed.idstatuscache] Found IDStatusCache 
                  plist at path: /Users/o/Library/Application               
                  Support/MobileSync/Backup/00008110-00127D0102EB801E/6b/6b9
                  7989189901ceaa4e5be9b7f05fb584120e27b                     
         ERROR    [mvt.ios.modules.mixed.idstatuscache] Error in running    
                  extraction from module IDStatusCache: Invalid file        
                  Traceback (most recent call last):                        
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/module
                  .py", line 167, in run_module                             
                      exec_or_profile("module.run()", globals(), locals())  
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/utils.
                  py", line 236, in exec_or_profile                         
                      exec(module, globals, locals)                         
                    File "<string>", line 1, in <module>                    
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/idstatuscache.py", line 111, in run                  
                      self._extract_idstatuscache_entries(self.file_path)   
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/idstatuscache.py", line 76, in                       
                  _extract_idstatuscache_entries                            
                      file_plist = plistlib.load(handle)                    
                                   ^^^^^^^^^^^^^^^^^^^^^                    
                    File                                                    
                  "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.fr
                  amework/Versions/3.11/lib/python3.11/plistlib.py", line   
                  878, in load                                              
                      raise InvalidFileException()                          
                  plistlib.InvalidFileException: Invalid file               
         INFO     [mvt.ios.modules.mixed.interactionc] Running module       
                  InteractionC...                                           
         INFO     [mvt.ios.modules.mixed.interactionc] Found InteractionC   
                  database at path: /Users/o/Library/Application            
                  Support/MobileSync/Backup/00008110-00127D0102EB801E/1f/1f5
                  a521220a3ad80ebfdc196978df8e7a2e49dee                     
         ERROR    [mvt.ios.modules.mixed.interactionc] Error in running     
                  extraction from module InteractionC: file is not a        
                  database                                                  
                  Traceback (most recent call last):                        
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/interactionc.py", line 287, in run                   
                      cur.execute(QUERIES[0])                               
                  sqlite3.OperationalError: near "AS": syntax error         
                                                                            
                  During handling of the above exception, another exception 
                  occurred:                                                 
                                                                            
                  Traceback (most recent call last):                        
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/interactionc.py", line 290, in run                   
                      cur.execute(QUERIES[1])                               
                  sqlite3.OperationalError: near "AS": syntax error         
                                                                            
                  During handling of the above exception, another exception 
                  occurred:                                                 
                                                                            
                  Traceback (most recent call last):                        
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/module
                  .py", line 167, in run_module                             
                      exec_or_profile("module.run()", globals(), locals())  
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/utils.
                  py", line 236, in exec_or_profile                         
                      exec(module, globals, locals)                         
                    File "<string>", line 1, in <module>                    
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/interactionc.py", line 293, in run                   
                      cur.execute(QUERIES[2])                               
                  sqlite3.DatabaseError: file is not a database             
         INFO     [mvt.ios.modules.mixed.locationd] Running module          
                  LocationdClients...                                       
         INFO     [mvt.ios.modules.mixed.locationd] Found Locationd Clients 
                  plist at path: /Users/o/Library/Application               
                  Support/MobileSync/Backup/00008110-00127D0102EB801E/a6/a69
                  0d7769cce8904ca2b67320b107c8fe5f79412                     
         ERROR    [mvt.ios.modules.mixed.locationd] Error in running        
                  extraction from module LocationdClients: Invalid file     
                  Traceback (most recent call last):                        
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/module
                  .py", line 167, in run_module                             
                      exec_or_profile("module.run()", globals(), locals())  
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/utils.
                  py", line 236, in exec_or_profile                         
                      exec(module, globals, locals)                         
                    File "<string>", line 1, in <module>                    
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/locationd.py", line 161, in run                      
                      self._extract_locationd_entries(self.file_path)       
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/locationd.py", line 137, in                          
                  _extract_locationd_entries                                
                      file_plist = plistlib.load(handle)                    
                                   ^^^^^^^^^^^^^^^^^^^^^                    
                    File                                                    
                  "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.fr
                  amework/Versions/3.11/lib/python3.11/plistlib.py", line   
                  878, in load                                              
                      raise InvalidFileException()                          
                  plistlib.InvalidFileException: Invalid file               
         INFO     [mvt.ios.modules.mixed.osanalytics_addaily] Running module
                  OSAnalyticsADDaily...                                     
         INFO     [mvt.ios.modules.mixed.osanalytics_addaily] Found         
                  com.apple.osanalytics.addaily plist at path:              
                  /Users/o/Library/Application                              
                  Support/MobileSync/Backup/00008110-00127D0102EB801E/f6/f65
                  b5fafc69bbd3c60be019c6e938e146825fa83                     
         ERROR    [mvt.ios.modules.mixed.osanalytics_addaily] Error in      
                  running extraction from module OSAnalyticsADDaily: Invalid
                  file                                                      
                  Traceback (most recent call last):                        
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/module
                  .py", line 167, in run_module                             
                      exec_or_profile("module.run()", globals(), locals())  
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/utils.
                  py", line 236, in exec_or_profile                         
                      exec(module, globals, locals)                         
                    File "<string>", line 1, in <module>                    
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/osanalytics_addaily.py", line 75, in run             
                      file_plist = plistlib.load(handle)                    
                                   ^^^^^^^^^^^^^^^^^^^^^                    
                    File                                                    
                  "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.fr
                  amework/Versions/3.11/lib/python3.11/plistlib.py", line   
                  878, in load                                              
                      raise InvalidFileException()                          
                  plistlib.InvalidFileException: Invalid file               
         INFO     [mvt.ios.modules.mixed.net_datausage] Running module      
                  Datausage...                                              
         INFO     [mvt.ios.modules.mixed.net_datausage] Found DataUsage     
                  database at path: /Users/o/Library/Application            
                  Support/MobileSync/Backup/00008110-00127D0102EB801E/0d/0d6
                  09c54856a9bb2d56729df1d68f2958a88426b                     
         ERROR    [mvt.ios.modules.mixed.net_datausage] Error in running    
                  extraction from module Datausage: file is not a database  
                  Traceback (most recent call last):                        
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/module
                  .py", line 167, in run_module                             
                      exec_or_profile("module.run()", globals(), locals())  
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/utils.
                  py", line 236, in exec_or_profile                         
                      exec(module, globals, locals)                         
                    File "<string>", line 1, in <module>                    
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/net_datausage.py", line 50, in run                   
                      self._extract_net_data()                              
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/n
                  et_base.py", line 42, in _extract_net_data                
                      cur.execute(                                          
                  sqlite3.DatabaseError: file is not a database             
         INFO     [mvt.ios.modules.mixed.safari_browserstate] Running module
                  SafariBrowserState...                                     
         ERROR    [mvt.ios.modules.mixed.safari_browserstate] The           
                  SafariBrowserState module database seems to be corrupted: 
                  failed to query Manifest.db: file is not a database       
         INFO     [mvt.ios.modules.mixed.safari_history] Running module     
                  SafariHistory...                                          
         ERROR    [mvt.ios.modules.mixed.safari_history] The SafariHistory  
                  module database seems to be corrupted: failed to query    
                  Manifest.db: file is not a database                       
         INFO     [mvt.ios.modules.mixed.tcc] Running module TCC...         
         INFO     [mvt.ios.modules.mixed.tcc] Found TCC database at path:   
                  /Users/o/Library/Application                              
                  Support/MobileSync/Backup/00008110-00127D0102EB801E/64/64d
                  0019cb3d46bfc8cce545a8ba54b93e7ea9347                     
         ERROR    [mvt.ios.modules.mixed.tcc] Error in running extraction   
                  from module TCC: file is not a database                   
                  Traceback (most recent call last):                        
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/module
                  .py", line 167, in run_module                             
                      exec_or_profile("module.run()", globals(), locals())  
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/utils.
                  py", line 236, in exec_or_profile                         
                      exec(module, globals, locals)                         
                    File "<string>", line 1, in <module>                    
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/tcc.py", line 222, in run                            
                      self.process_db(self.file_path)                       
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/tcc.py", line 102, in process_db                     
                      cur.execute(                                          
                  sqlite3.DatabaseError: file is not a database             
         INFO     [mvt.ios.modules.mixed.sms] Running module SMS...         
         INFO     [mvt.ios.modules.mixed.sms] Found SMS database at path:   
                  /Users/o/Library/Application                              
                  Support/MobileSync/Backup/00008110-00127D0102EB801E/3d/3d0
                  d7e5fb2ce288813306e4d4636395e047a3d28                     
         ERROR    [mvt.ios.modules.mixed.sms] Error in running extraction   
                  from module SMS: file is not a database                   
                  Traceback (most recent call last):                        
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/module
                  .py", line 167, in run_module                             
                      exec_or_profile("module.run()", globals(), locals())  
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/utils.
                  py", line 236, in exec_or_profile                         
                      exec(module, globals, locals)                         
                    File "<string>", line 1, in <module>                    
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/sms.py", line 119, in run                            
                      raise exc                                             
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/sms.py", line 91, in run                             
                      cur.execute(                                          
                  sqlite3.DatabaseError: file is not a database             
         INFO     [mvt.ios.modules.mixed.sms_attachments] Running module    
                  SMSAttachments...                                         
         INFO     [mvt.ios.modules.mixed.sms_attachments] Found SMS database
                  at path: /Users/o/Library/Application                     
                  Support/MobileSync/Backup/00008110-00127D0102EB801E/3d/3d0
                  d7e5fb2ce288813306e4d4636395e047a3d28                     
         ERROR    [mvt.ios.modules.mixed.sms_attachments] Error in running  
                  extraction from module SMSAttachments: file is not a      
                  database                                                  
                  Traceback (most recent call last):                        
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/module
                  .py", line 167, in run_module                             
                      exec_or_profile("module.run()", globals(), locals())  
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/utils.
                  py", line 236, in exec_or_profile                         
                      exec(module, globals, locals)                         
                    File "<string>", line 1, in <module>                    
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/sms_attachments.py", line 77, in run                 
                      cur.execute(                                          
                  sqlite3.DatabaseError: file is not a database             
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics]   
                  Running module WebkitResourceLoadStatistics...            
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics]   
                  Unable to find WebKit observations.db: failed to query    
                  Manifest.db: file is not a database                       
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics]   
                  The WebkitResourceLoadStatistics module produced no       
                  detections!                                               
         INFO     [mvt.ios.modules.mixed.webkit_session_resource_log]       
                  Running module WebkitSessionResourceLog...                
         ERROR    [mvt.ios.modules.mixed.webkit_session_resource_log] The   
                  WebkitSessionResourceLog module database seems to be      
                  corrupted: failed to query Manifest.db: file is not a     
                  database                                                  
         INFO     [mvt.ios.modules.mixed.whatsapp] Running module           
                  Whatsapp...                                               
         INFO     [mvt.ios.modules.mixed.whatsapp] There might be no data to
                  extract by module Whatsapp: unable to find the module's   
                  database file                                             
         INFO     [mvt.ios.modules.mixed.shortcuts] Running module          
                  Shortcuts...                                              
         INFO     [mvt.ios.modules.mixed.shortcuts] Found Shortcuts database
                  at path: /Users/o/Library/Application                     
                  Support/MobileSync/Backup/00008110-00127D0102EB801E/5b/5b4
                  d0b44b5990f62b9f4d34ad8dc382bf0b01094                     
         ERROR    [mvt.ios.modules.mixed.shortcuts] Error in running        
                  extraction from module Shortcuts: file is not a database  
                  Traceback (most recent call last):                        
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/module
                  .py", line 167, in run_module                             
                      exec_or_profile("module.run()", globals(), locals())  
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/utils.
                  py", line 236, in exec_or_profile                         
                      exec(module, globals, locals)                         
                    File "<string>", line 1, in <module>                    
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/shortcuts.py", line 90, in run                       
                      cur.execute(                                          
                  sqlite3.DatabaseError: file is not a database             
         INFO     [mvt.ios.modules.mixed.applications] Running module       
                  Applications...                                           
         INFO     [mvt.ios.modules.mixed.applications] Extracted a total of 
                  39 applications                                           
         INFO     [mvt.ios.modules.mixed.applications] The Applications     
                  module produced no detections!                            
         INFO     [mvt.ios.modules.mixed.calendar] Running module           
                  Calendar...                                               
         INFO     [mvt.ios.modules.mixed.calendar] Found calendar database  
                  at path: /Users/o/Library/Application                     
                  Support/MobileSync/Backup/00008110-00127D0102EB801E/20/204
                  1457d5fe04d39d0ab481178355df6781e6858                     
         ERROR    [mvt.ios.modules.mixed.calendar] Error in running         
                  extraction from module Calendar: file is not a database   
                  Traceback (most recent call last):                        
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/module
                  .py", line 167, in run_module                             
                      exec_or_profile("module.run()", globals(), locals())  
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/utils.
                  py", line 236, in exec_or_profile                         
                      exec(module, globals, locals)                         
                    File "<string>", line 1, in <module>                    
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/calendar.py", line 142, in run                       
                      self._parse_calendar_db()                             
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/calendar.py", line 88, in _parse_calendar_db         
                      cur.execute(                                          
                  sqlite3.DatabaseError: file is not a database             
         INFO     [mvt.ios.modules.mixed.global_preferences] Running module 
                  GlobalPreferences...                                      
         INFO     [mvt.ios.modules.mixed.global_preferences] Found Global   
                  Preference database at path: /Users/o/Library/Application 
                  Support/MobileSync/Backup/00008110-00127D0102EB801E/0d/0dc
                  926a1810f7aee4e8f38793ed788701f93bf9d                     
         ERROR    [mvt.ios.modules.mixed.global_preferences] Error in       
                  running extraction from module GlobalPreferences: Invalid 
                  file                                                      
                  Traceback (most recent call last):                        
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/module
                  .py", line 167, in run_module                             
                      exec_or_profile("module.run()", globals(), locals())  
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/common/utils.
                  py", line 236, in exec_or_profile                         
                      exec(module, globals, locals)                         
                    File "<string>", line 1, in <module>                    
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/global_preferences.py", line 61, in run              
                      self.process_file(self.file_path)                     
                    File                                                    
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m
                  ixed/global_preferences.py", line 49, in process_file     
                      data = plistlib.load(handle)                          
                             ^^^^^^^^^^^^^^^^^^^^^                          
                    File                                                    
                  "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.fr
                  amework/Versions/3.11/lib/python3.11/plistlib.py", line   
                  878, in load                                              
                      raise InvalidFileException()                          
                  plistlib.InvalidFileException: Invalid file               
o@iMac-Quark mvt % >....                                                    

                  "/usr/local/lib/python3.11/site-packages/mvt/common/utils. 
                  py", line 236, in exec_or_profile                          
                      exec(module, globals, locals)                          
                    File "<string>", line 1, in <module>                     
                    File                                                     
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m 
                  ixed/global_preferences.py", line 61, in run               
                      self.process_file(self.file_path)                      
                    File                                                     
                  "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/m 
                  ixed/global_preferences.py", line 49, in process_file      
                      data = plistlib.load(handle)                           
                             ^^^^^^^^^^^^^^^^^^^^^                           
                    File                                                     
                  "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.fr 
                  amework/Versions/3.11/lib/python3.11/plistlib.py", line    
                  878, in load                                               
                      raise InvalidFileException()                           
                  plistlib.InvalidFileException: Invalid file

**Comment by DrWhax** [comment]
The sqlite database could be corrupt. You could either try a new backup or try and repair the sqlite like: https://www.sqlite.org/recovery.html

Don't forget to rename the sqlite after and put it in the right position.

**Comment by DonnchaC** [comment]
@sealvessel Have you decrypted the backup first before running MVT on the decrypted folder?

**Comment by sealvessel** [comment]
> @sealvessel Have you decrypted the backup first before running MVT on the decrypted folder?

How do I decrypt it? What command should I use. 
Also I'm new. How would I repair the sqlite3.

**Comment by sealvessel** [comment]
I ran the command on a decrypted backup and now it just freezes and shows this screen for a long time without any loading symbol. 
<img width="532" alt="image" src="https://github.com/mvt-project/mvt/assets/66351949/c584201f-2d79-43ce-8659-09dde4664939">

**Comment by sealvessel** [comment]
> The sqlite database could be corrupt. You could either try a new backup or try and repair the sqlite like: https://www.sqlite.org/recovery.html
> 
> Don't forget to rename the sqlite after and put it in the right position.

I'm using macOS it doesn't have the same syntax.

**Comment by sealvessel** [comment]
This seems to work now when I decrypted the backup. It just shows all "info" cards. 
What console messsage indicates an infection vector?

**Comment by sealvessel** [comment]
<img width="747" alt="image" src="https://github.com/mvt-project/mvt/assets/66351949/e3e4bc85-97a2-4244-9ea3-8376432461c6">
So this is successful? There is no indication of mercenary spyware on the device.

**Comment by sealvessel** [comment]
Can anyone reply? What is the verdict. Is what I did correct?

**Comment by Te-k** [comment]
From the screenshot you shared above, it looks like MVT ran correctly.

**Comment by sealvessel** [comment]
> From the screenshot you shared above, it looks like MVT ran correctly.

I still don't know how to make it work with an encrypted backup. 
I did the key things and encryption but I'm not sure which is which technical term. THere are so many definitions of what comprises a "key" I put my backup password, I put the encoded string, it still doesn't work.

**Comment by Te-k** [comment]
You need to decrypt the backup first with `decrypt-backup` and then check the decrypted backup with `check-backup`. Decrypt backup will ask for your backup password. See the doc there https://docs.mvt.re/en/latest/ios/backup/check/#decrypting-a-backup
