### ISSUE TITLE
LocationdClients Module : error "'int' object does not support item assignment "

### ISSUE THREAD

**Issue by lnabergoi** [mvt-project/mvt#403]
```
         INFO     [mvt.ios.modules.mixed.locationd] Running module LocationdClients...                                                                               
         INFO     [mvt.ios.modules.mixed.locationd] Found Locationd Clients plist at path: ../decrypted_backup/a6/a690d7769cce8904ca2b67320b107c8fe5f79412           
         ERROR    [mvt.ios.modules.mixed.locationd] Error in running extraction from module LocationdClients: 'int' object does not support item assignment          
                  Traceback (most recent call last):                                                                                                                 
                    File "/usr/local/lib/python3.11/site-packages/mvt/common/module.py", line 167, in run_module                                                     
                      exec_or_profile("module.run()", globals(), locals())                                                                                           
                    File "/usr/local/lib/python3.11/site-packages/mvt/common/utils.py", line 236, in exec_or_profile                                                 
                      exec(module, globals, locals)                                                                                                                  
                    File "<string>", line 1, in <module>                                                                                                             
                    File "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/mixed/locationd.py", line 139, in run                                              
                      self._extract_locationd_entries(self.file_path)                                                                                                
                    File "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/mixed/locationd.py", line 128, in _extract_locationd_entries                       
                      result["package"] = key                                                                                                                        
                      ~~~~~~^^^^^^^^^^^                                                                                                                              
                  TypeError: 'int' object does not support item assignment    
```
Environment Info:

 Product Type: iPhone12,3 (iPhone 11 Pro)                                                                      
 Product Version: 17.0.2    (iPhone 11 Pro)                                                                                                                              
 iTunes Version: 12.10.5     

Host machine: macOS 13.6 (22G120)

**Comment by Te-k** [comment]
Hi, 

Thanks for reporting this bug. Could you try with the latest version from github? I think I fixed this bug earlier this week but I can push it on pypi if it fixes your issue

**Comment by j-siddle** [comment]
I also encountered this issue and using the latest version of mvt from GitHub resolved the issue - thanks. I can provide further evidence of the successful run if required.

**Comment by Te-k** [comment]
Great, thanks for the feedback
