### ISSUE TITLE
DatabaseError on mvt-ios decrypt-backup

### ISSUE THREAD

**Issue by tomjaroli** [mvt-project/mvt#48]
## Command
I am running the following command:
`mvt-ios decrypt-backup -p {password-placeholder} -d ./mvt-backup ~/Library/Application\ Support/MobileSync/Backup/{device-id}`

## Error log
The command above fails and produces the log below

```
Traceback (most recent call last):
  File "/usr/local/bin/mvt-ios", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mvt/ios/cli.py", line 56, in decrypt_backup
    backup.decrypt_with_password(password)
  File "/usr/local/lib/python3.9/site-packages/mvt/ios/decrypt.py", line 83, in decrypt_with_password
    self._process_backup()
  File "/usr/local/lib/python3.9/site-packages/mvt/ios/decrypt.py", line 36, in _process_backup
    for item in self._backup.getBackupFilesList():
  File "/usr/local/lib/python3.9/site-packages/iOSbackup/__init__.py", line 399, in getBackupFilesList
    backupFiles = catalog.cursor().execute(f"SELECT * FROM Files ORDER BY domain,relativePath").fetchall()
sqlite3.DatabaseError: file is not a database
```

**Comment by nonstatiq** [comment]
Have the same issue...

**Comment by Te-k** [comment]
Do you have access rights to this file? Can you do a file on it? Open it with sqlite?

**Comment by tomjaroli** [comment]
> Do you have access rights to this file? Can you do a file on it? Open it with sqlite?

Yes, I have access and I can list the tables of the db.

**Comment by Te-k** [comment]
Does your terminal have access to the backup folder? On recent Mac OS you have to give full disk access to your terminal

**Comment by tomjaroli** [comment]
It has full disk access.

**Comment by botherder** [comment]
Can you share the output of `ls -l ~/Library/Application\ Support/MobileSync/Backup/{device-id}` and `file ~/Library/Application\ Support/MobileSync/Backup/{device-id}/Manifest.db` ?

**Comment by tomjaroli** [comment]
> file ~/Library/Application\ Support/MobileSync/Backup/{device-id}/Manifest.db

This is only part of the output, but there are a lot more of these files
<img width="1680" alt="Screenshot 2021-08-20 at 12 32 37" src="https://user-images.githubusercontent.com/3617451/130221027-1962efc1-ff3b-458e-9919-214542970a2a.png">

<img width="1451" alt="Screenshot 2021-08-20 at 12 34 34" src="https://user-images.githubusercontent.com/3617451/130221125-b7b00df0-8bd7-4720-852d-bdf413c1d1e4.png">

**Comment by botherder** [comment]
It looks like it's not encrypted though, otherwise the file command should just return "data" for Manifest.db.

**Comment by tomjaroli** [comment]
Wow that's interesting! I'm not sure what the issue is, because I encrypted the backup tho.
Thank you for the answer, I will keep trying!
