### ISSUE TITLE
Error in extraction: unable to open database file

### ISSUE THREAD

**Issue by rslid** [mvt-project/mvt#49]
`mvt-ios check-backup` on a new backup created  with `idevicebackup2 backup --full `and decrypted with `mvt-ios decrypt-backup ` returns the following error:

`INFO     [mvt.ios.cli] Checking iTunes backup located at: ./decrypted                                                                                                          
         INFO     [mvt.ios.modules.fs.safari_browserstate] Running module SafariBrowserState...                                                                                         
         INFO     [mvt.ios.modules.fs.safari_browserstate] Found Safari browser state database at path: ./decrypted/3a/3a47b0981ed7c10f3e2800aa66bac96a3b5db28e                         
         ERROR    [mvt.ios.modules.fs.safari_browserstate] Error in running extraction from module SafariBrowserState: unable to open database file                                     
                  Traceback (most recent call last):                                                                                                                                    
                    File "/usr/local/lib/python3.9/site-packages/mvt/common/module.py", line 134, in run_module                                                                         
                      module.run()                                                                                                                                                      
                    File "/usr/local/lib/python3.9/site-packages/mvt/ios/modules/fs/safari_browserstate.py", line 65, in run                                                            
                      cur.execute("""SELECT                                                                                                                                             
                  sqlite3.OperationalError: unable to open database file`

Of course I tried proposed solution with .clone sqlite command

**Comment by Te-k** [comment]
Have you tried opening `./decrypted/3a/3a47b0981ed7c10f3e2800aa66bac96a3b5db28e` with sqlite? Is it valid?

**Comment by botherder** [comment]
Closing this for inactivity. If it remains an issue please note here.
