### ISSUE TITLE
check-adb throws error "The Android device does not seem to have a `su` binary. Cannot run this module."

### ISSUE THREAD

**Issue by AntonLydike** [mvt-project/mvt#5]
Running the check-adb command fails because of missing `su` binary on the device.

```
$ mvt-android check-adb
11:06:01 INFO     [mvt.android.cli] Checking Android through adb bridge                       
         INFO     [mvt.android.modules.adb.chrome_history] Running module ChromeHistory...    
11:06:02 ERROR    [mvt.android.modules.adb.chrome_history] Error in running extraction from   
                  module ChromeHistory: The Android device does not seem to have a `su`       
                  binary. Cannot run this module.                                             
                  Traceback (most recent call last):                                          
                    File "/tmp/mvt/mvt/common/module.py", line 134, in run_module             
                      module.run()                                                            
                    File "/tmp/mvt/mvt/android/modules/adb/chrome_history.py", line 69, in run
                      self._adb_process_file(os.path.join("/", CHROME_HISTORY_PATH),          
                    File "/tmp/mvt/mvt/android/modules/adb/base.py", line 135, in             
                  _adb_process_file                                                           
                      self._adb_root_or_die()                                                 
                    File "/tmp/mvt/mvt/android/modules/adb/base.py", line 105, in             
                  _adb_root_or_die                                                            
                      raise Exception("The Android device does not seem to have a `su` binary.
                  Cannot run this module.")                                                   
                  Exception: The Android device does not seem to have a `su` binary. Cannot   
                  run this module.                                                            
         INFO     [mvt.android.modules.adb.sms] Running module SMS...                         
11:06:03 ERROR    [mvt.android.modules.adb.sms] The Android device does not seem to have a    
                  `su` binary. Cannot run this module.                                        
         INFO     [mvt.android.modules.adb.whatsapp] Running module Whatsapp...               
11:06:04 ERROR    [mvt.android.modules.adb.whatsapp] The Android device does not seem to have 
                  a `su` binary. Cannot run this module.                                      
         INFO     [mvt.android.modules.adb.processes] Running module Processes...             
         INFO     [mvt.android.modules.adb.processes] Extracted records on a total of 1       
                  processes                                                                   
         INFO     [mvt.android.modules.adb.dumpsys_batterystats] Running module               
                  DumpsysBatterystats...                                                      
11:06:05 INFO     [mvt.android.modules.adb.dumpsys_procstats] Running module                  
                  DumpsysProcstats...                                                         
11:06:06 INFO     [mvt.android.modules.adb.dumpsys_packages] Running module DumpsysPackages...
11:06:07 INFO     [mvt.android.modules.adb.packages] Running module Packages...               
11:06:21 INFO     [mvt.android.modules.adb.packages] Extracted at total of 256 installed      
                  package names                                                               
         INFO     [mvt.android.modules.adb.rootbinaries] Running module RootBinaries...       

```

**Comment by Te-k** [comment]
Is your android phone rooted?

**Comment by AntonLydike** [comment]
No, the phone used is not rooted.

**Comment by sarvang00** [comment]
Facing the same issue here.

**Comment by KatzeMau** [comment]
On non rooted phones some things do not work

**Comment by diehard88** [comment]
same here.

tab s7+ non-rooted.


however, mvt works with my tab s6 which is rooted.

**Comment by KatzeMau** [comment]
I think for su scans the device must be rooted

**Comment by pwfraley** [comment]
I have the same problem.  So basically to be able to run this tool, I need to root my device, which might make it vulnarable to attacks and also basically wipes my device?
Somehow seems contra productive, or am I misunderstanding something here?

**Comment by KatzeMau** [comment]
@pwfraley 
I wouldn't root it, MVT can scan most parts of the android phone (without root)
And yes, root make it more vulnarable to attacks

**Comment by kmrcs** [comment]
Has anyone found a trick as a workaround for this, or did you go with rooting the device? :)

**Comment by botherder** [comment]
No, it is not recommended to root your own device. Some modules however can only function with root available. Simply you won't be able to run those modules.
