### ISSUE TITLE
Error in running extraction from module SMS: expected string or bytes-like object, got 'NoneType'   

### ISSUE THREAD

**Issue by stereotypy** [mvt-project/mvt#526]
When running MVT on android I'm getting this crash on SMS

```ERROR    [mvt.android.modules.adb.sms] Error in running extraction from module SMS: expected string or bytes-like object, got 'NoneType'           
                  Traceback (most recent call last):                                                                                                        
                    File "/home/x/.local/share/pipx/venvs/mvt/lib/python3.12/site-packages/mvt/common/module.py", line 167, in run_module              
                      exec_or_profile("module.run()", globals(), locals())                                                                                  
                    File "/home/x/.local/share/pipx/venvs/mvt/lib/python3.12/site-packages/mvt/common/utils.py", line 262, in exec_or_profile          
                      exec(module, globals, locals)                                                                                                         
                    File "<string>", line 1, in <module>                                                                                                    
                    File "/home/x/.local/share/pipx/venvs/mvt/lib/python3.12/site-packages/mvt/android/modules/adb/sms.py", line 156, in run           
                      self._adb_process_file(                                                                                                               
                    File "/home/x/.local/share/pipx/venvs/mvt/lib/python3.12/site-packages/mvt/android/modules/adb/base.py", line 301, in              
                  _adb_process_file                                                                                                                         
                      process_routine(local_path)                                                                                                           
                    File "/home/x/.local/share/pipx/venvs/mvt/lib/python3.12/site-packages/mvt/android/modules/adb/sms.py", line 116, in _parse_db     
                      links = check_for_links(message["body"])                                                                                              
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                              
                    File "/home/x/.local/share/pipx/venvs/mvt/lib/python3.12/site-packages/mvt/common/utils.py", line 151, in check_for_links          
                      return re.findall(r"(?P<url>https?://[^\s]+)", text, re.IGNORECASE)                                                                   
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                   
                    File "/usr/lib/python3.12/re/__init__.py", line 217, in findall                                                                         
                      return _compile(pattern, flags).findall(string)                                                                                       
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                       
                  TypeError: expected string or bytes-like object, got 'NoneType'  
```

**Comment by Te-k** [comment]
It sounds like you have an empty body in your SMS database, first time I see that but we should fix that. I'll try to do it later this week

**Comment by Te-k** [comment]
Hi, this fix is merged, could you try now?
