### ISSUE TITLE
No colum ZLIVEUSAGE.ZWIFIIN in datausage

### ISSUE THREAD

**Issue by besendorf** [mvt-project/mvt#531]
```
ERROR    - Error in running extraction from module Datausage: no such column: ZLIVEUSAGE.ZWIFIIN
║ Traceback (most recent call last):
║   File "/usr/local/lib/python3.11/site-packages/mvt/common/module.py", line 167, in run_module
║     exec_or_profile("module.run()", globals(), locals())
║   File "/usr/local/lib/python3.11/site-packages/mvt/common/utils.py", line 262, in exec_or_profile
║     exec(module, globals, locals)
║   File "<string>", line 1, in <module>
║   File "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/mixed/net_datausage.py", line 50, in run
║     self._extract_net_data()
║   File "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/net_base.py", line 42, in _extract_net_data
║     cur.execute(
║ sqlite3.OperationalError: no such column: ZLIVEUSAGE.ZWIFIIN
```

**Comment by Te-k** [comment]
Thanks for reporting it @besendorf !
Could you please share with us the iOS version and the ZLIVEUSAGE table format? (you can get it with [sqlite .schema command](https://www.sqlite.org/cli.html)) (here or in private).

Thanks!

**Comment by soreore** [comment]
> Thanks for reporting it @besendorf ! Could you please share with us the iOS version and the ZLIVEUSAGE table format? (you can get it with [sqlite .schema command](https://www.sqlite.org/cli.html)) (here or in private).
> 
> Thanks!

is it a virus?

**Comment by besendorf** [comment]
> Thanks for reporting it @besendorf ! Could you please share with us the iOS version and the ZLIVEUSAGE table format? (you can get it with [sqlite .schema command](https://www.sqlite.org/cli.html)) (here or in private).
> 
> Thanks!

Here the schema for the table:

```
CREATE TABLE ZLIVEUSAGE ( Z_PK INTEGER PRIMARY KEY, Z_ENT INTEGER, Z_OPT INTEGER, ZKIND INTEGER, ZMETADATA INTEGER, ZTAG INTEGER, ZHASPROCESS INTEGER, ZBILLCYCLEEND TIMESTAMP, ZTIMESTAMP TIMESTAMP, ZWWANIN FLOAT, ZWWANOUT FLOAT, ZBUNDLENAME VARCHAR, ZPROCNAME VARCHAR );
CREATE INDEX ZLIVEUSAGE_ZHASPROCESS_INDEX ON ZLIVEUSAGE (ZHASPROCESS);
```

**Comment by Te-k** [comment]
It should be fixed with the latest commit

**Comment by besendorf** [comment]
> I've tried using the MVT-iOS version via pipx install a week ago, I still get the same problem unfortunately

Only releases are pushed to pypi. Please ceck out the source and install with `pip install .` to use the latest versions
