### ISSUE TITLE
new bug: JSON DECODE Error when loading results from logcat.txt

### ISSUE THREAD

**Issue by azeemh** [mvt-project/mvt#574]
new bug shows from old phone check.

```azeem@x9:~$ mvt-android check-iocs mvtcheck


        MVT - Mobile Verification Toolkit
                https://mvt.re
                Version: 2.5.4
                Indicators updates checked recently, next automatic check in 12 hours


12:04:05 INFO     [mvt.common.cmd_check_iocs] Parsing STIX2 indicators file at path                                                                                                             
                  /home/azeem/.local/share/mvt/indicators/raw.githubusercontent.com_mvt-project_mvt-indicators_main_2023-06_01_operation_triangulation_operation_triangulation.stix2            
         INFO     [mvt.common.cmd_check_iocs] Parsing STIX2 indicators file at path                                                                                                             
                  /home/azeem/.local/share/mvt/indicators/raw.githubusercontent.com_AmnestyTech_investigations_master_2021-07-18_nso_pegasus.stix2                                              
         INFO     [mvt.common.cmd_check_iocs] Parsing STIX2 indicators file at path                                                                                                             
                  /home/azeem/.local/share/mvt/indicators/raw.githubusercontent.com_mvt-project_mvt-indicators_main_intellexa_predator_predator.stix2                                           
         INFO     [mvt.common.cmd_check_iocs] Parsing STIX2 indicators file at path                                                                                                             
                  /home/azeem/.local/share/mvt/indicators/raw.githubusercontent.com_mvt-project_mvt-indicators_main_2023-04-11_quadream_kingspawn.stix2                                         
         INFO     [mvt.common.cmd_check_iocs] Parsing STIX2 indicators file at path                                                                                                             
                  /home/azeem/.local/share/mvt/indicators/raw.githubusercontent.com_AmnestyTech_investigations_master_2023-03-29_android_campaign_malware.stix2                                 
12:04:06 INFO     [mvt.common.cmd_check_iocs] Parsing STIX2 indicators file at path                                                                                                             
                  /home/azeem/.local/share/mvt/indicators/raw.githubusercontent.com_AssoEchap_stalkerware-indicators_master_generated_stalkerware.stix2                                         
12:04:07 INFO     [mvt.common.cmd_check_iocs] Parsing STIX2 indicators file at path                                                                                                             
                  /home/azeem/.local/share/mvt/indicators/raw.githubusercontent.com_mvt-project_mvt-indicators_main_2022-06-23_rcs_lab_rcs.stix2                                                
         INFO     [mvt.common.cmd_check_iocs] Parsing STIX2 indicators file at path                                                                                                             
                  /home/azeem/.local/share/mvt/indicators/raw.githubusercontent.com_mvt-project_mvt-indicators_main_2023-07-25_wyrmspy_dragonegg_wyrmspy_dragonegg.stix2                        
         INFO     [mvt.common.cmd_check_iocs] Loaded a total of 9690 unique indicators                                                                                                          
         INFO     [mvt.common.cmd_check_iocs] Checking stored results against provided indicators...                                                                                            
         INFO     [mvt.common.cmd_check_iocs] Loading results from "sms.json" with module SMS                                                                                                   
         INFO     [mvt.android.modules.backup.sms] Loaded 137 results from "mvtcheck/sms.json"                                                                                                  
         INFO     [mvt.common.cmd_check_iocs] Loading results from "sms.json" with module SMS                                                                                                   
         INFO     [mvt.android.modules.adb.sms] Loaded 137 results from "mvtcheck/sms.json"                                                                                                     
12:04:08 INFO     [mvt.common.cmd_check_iocs] Loading results from "dumpsys_dbinfo.json" with module DumpsysDBInfo                                                                              
         INFO     [mvt.android.modules.adb.dumpsys_dbinfo] Loaded 2005 results from "mvtcheck/dumpsys_dbinfo.json"                                                                              
12:04:11 INFO     [mvt.common.cmd_check_iocs] Loading results from "processes.json" with module Processes                                                                                       
         INFO     [mvt.android.modules.adb.processes] Loaded 725 results from "mvtcheck/processes.json"                                                                                         
         INFO     [mvt.common.cmd_check_iocs] Loading results from "dumpsys_activities.json" with module DumpsysActivities                                                                      
         INFO     [mvt.android.modules.adb.dumpsys_activities] Loaded 4241 results from "mvtcheck/dumpsys_activities.json"                                                                      
12:04:12 INFO     [mvt.common.cmd_check_iocs] Loading results from "selinux_status.json" with module SELinuxStatus                                                                              
         INFO     [mvt.android.modules.adb.selinux_status] Loaded 1 results from "mvtcheck/selinux_status.json"                                                                                 
         INFO     [mvt.common.cmd_check_iocs] Loading results from "dumpsys_battery_daily.json" with module DumpsysBatteryDaily                                                                 
         INFO     [mvt.android.modules.adb.dumpsys_battery_daily] Loaded 67 results from "mvtcheck/dumpsys_battery_daily.json"                                                                  
         INFO     [mvt.common.cmd_check_iocs] Loading results from "files.json" with module Files                                                                                               
         INFO     [mvt.android.modules.adb.files] Loaded 409080 results from "mvtcheck/files.json"                                                                                              
12:04:29 INFO     [mvt.common.cmd_check_iocs] Loading results from "dumpsys_appops.json" with module DumpsysAppOps                                                                              
         INFO     [mvt.android.modules.adb.dumpsys_appops] Loaded 207 results from "mvtcheck/dumpsys_appops.json"                                                                               
12:04:30 INFO     [mvt.android.modules.adb.dumpsys_appops] Package com.android.chrome with REQUEST_INSTALL_PACKAGES permission                                                                  
         INFO     [mvt.android.modules.adb.dumpsys_appops] Package org.fdroid.fdroid with REQUEST_INSTALL_PACKAGES permission                                                                   
         INFO     [mvt.common.cmd_check_iocs] Loading results from "dumpsys_accessibility.json" with module DumpsysAccessibility                                                                
         INFO     [mvt.android.modules.adb.dumpsys_accessibility] Loaded 9 results from "mvtcheck/dumpsys_accessibility.json"                                                                   
         INFO     [mvt.common.cmd_check_iocs] Loading results from "logcat.txt" with module Logcat                                                                                              
Traceback (most recent call last):
  File "/home/azeem/.local/bin/mvt-android", line 8, in <module>
    sys.exit(cli())
  File "/home/azeem/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/azeem/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/azeem/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/azeem/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/azeem/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/azeem/.local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/azeem/.local/lib/python3.8/site-packages/mvt/android/cli.py", line 396, in check_iocs
    cmd.run()
  File "/home/azeem/.local/lib/python3.8/site-packages/mvt/common/cmd_check_iocs.py", line 65, in run
    m = iocs_module.from_json(
  File "/home/azeem/.local/lib/python3.8/site-packages/mvt/common/module.py", line 72, in from_json
    results = json.load(handle)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by ping2A** [comment]
I guess this issue is now fixed.

**Comment by Te-k** [comment]
Closing then, feel free to reopen @azeemh if you still encounter this problem
