### ISSUE TITLE
SafariBrowserState: no such table: tabs

### ISSUE THREAD

**Issue by besendorf** [mvt-project/mvt#578]
```
ERROR    - Error in running extraction from module SafariBrowserState: no such table: tabs
║ Traceback (most recent call last):
║   File "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/mixed/safari_browserstate.py", line 83, in _process_browser_state_db
║     cur.execute(
║ sqlite3.OperationalError: no such table: tabs
║ 
║ During handling of the above exception, another exception occurred:
║ 
║ Traceback (most recent call last):
║   File "/usr/local/lib/python3.11/site-packages/mvt/common/module.py", line 167, in run_module
║     exec_or_profile("module.run()", globals(), locals())
║   File "/usr/local/lib/python3.11/site-packages/mvt/common/utils.py", line 262, in exec_or_profile
║     exec(module, globals, locals)
║   File "<string>", line 1, in <module>
║   File "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/mixed/safari_browserstate.py", line 172, in run
║     self._process_browser_state_db(browserstate_path)
║   File "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/mixed/safari_browserstate.py", line 98, in _process_browser_state_db
║     cur.execute(
║ sqlite3.OperationalError: no such table: tabs
```

**Comment by Te-k** [comment]
I have the same issue on a phone I am testing, I think in some cases the database is empty. Could you please check if you can get the schema of your database?

**Comment by roaree** [comment]
Let's just catch the table not existing error gracefully
