### ISSUE TITLE
TCC: no such table: access

### ISSUE THREAD

**Issue by besendorf** [mvt-project/mvt#579]
```
ERROR    - Error in running extraction from module TCC: no such table: access
║ Traceback (most recent call last):
║   File "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/mixed/tcc.py", line 102, in process_db
║     cur.execute(
║ sqlite3.OperationalError: no such table: access
║ 
║ During handling of the above exception, another exception occurred:
║ 
║ Traceback (most recent call last):
║   File "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/mixed/tcc.py", line 111, in process_db
║     cur.execute(
║ sqlite3.OperationalError: no such table: access
║ 
║ During handling of the above exception, another exception occurred:
║ 
║ Traceback (most recent call last):
║   File "/usr/local/lib/python3.11/site-packages/mvt/common/module.py", line 167, in run_module
║     exec_or_profile("module.run()", globals(), locals())
║   File "/usr/local/lib/python3.11/site-packages/mvt/common/utils.py", line 262, in exec_or_profile
║     exec(module, globals, locals)
║   File "<string>", line 1, in <module>
║   File "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/mixed/tcc.py", line 222, in run
║     self.process_db(self.file_path)
║   File "/usr/local/lib/python3.11/site-packages/mvt/ios/modules/mixed/tcc.py", line 119, in process_db
║     cur.execute(
║ sqlite3.OperationalError: no such table: access
```

**Comment by besendorf** [comment]
I lost the sysdiagnose that caused this bug due to our file retention policy. Anyone got one with the same error?

**Comment by roaree** [comment]
For this one, let's try catch that `sqlite3.OperationalError` anyways gracefully.
